### ISSUE TITLE
no DirectCompute

### ISSUE THREAD

**Issue by dimwap** [dartraiden/NVIDIA-patcher#10]
In the latest release (536.40), only the name changes from P106 to 1060, and no new features appear, for example, there is no checkmark on DirectCompute.

**Comment by dartraiden** [comment]
If your Windows does not have a July update can you please try to patch the latest official driver with the [old patch](https://github.com/dartraiden/NVIDIA-patcher/tree/old_patcher)?

**Comment by dimwap** [comment]
https://www.youtube.com/watch?v=dkE4aAVUIzU
Already found a solution, editing the registry.
Уже нашел решение. Нужно реестр подредактировать. Появились галочки.

**Comment by dartraiden** [comment]
Попробую угадать: сначала винда поставила автоматически драйвер, а уже поверх был поставлен модифицированный? Без чистки?

**Comment by dimwap** [comment]
Боюсь использовать DDU он какой-то подозрительный

**Comment by dartraiden** [comment]
Тогда понятно: винда ставит драйвер на P106-100 и в реестр засаживается ключик AdapterType. Дальше поверх ставится драйвер на 1060, который при установке ключик создавать не должен, но ключик-то уже есть, и он отрубает 3D-ускорение.
