### ISSUE TITLE
P106 gpus can render H264

### ISSUE THREAD

**Issue by benhur90** [dartraiden/NVIDIA-patcher#102]
there could be a possible  chance that the gpu have nvenc support but had been disabled by it's own firmware. Youtube supports rendering on my P106 90 but it's got a little frame drop. first Youtube will render on the CPU then it will start to switch to the GPU which renders around from 20% to 35%. The frame drop is probably caused by poor compatbility

**Comment by dartraiden** [comment]
Perhaps, but no one has yet discovered a way to modify the firmware.
