### ISSUE TITLE
CMP 100-210 support

### ISSUE THREAD

**Issue by masterdeejay** [dartraiden/NVIDIA-patcher#105]
Please add support to this card. 

TitanV, Quadro, Tesla V100 drivers works for this card (manual install) but i think it's slower in Cuda, which it should be (not sure if the tensor cores are working). Your modded driver can help with this?
Also works in TCC and WDDM mode with tesla drivers.
(overclocked)
![139440_gzq5j9nm9eiwahn3_v1001](https://github.com/dartraiden/NVIDIA-patcher/assets/165884208/0d0f2b43-0ce4-42ff-999d-781c6e316390)
(stock)
![139440_x7jfgbx463hqzr84_titanvdriver](https://github.com/dartraiden/NVIDIA-patcher/assets/165884208/cb9e83d8-1fe1-42a9-8ee9-652892d75f5a)

Pcie lanes are just missing caps, i will repair them.
![139440_aja63jewwy9gujrz_139440_ovg6uafazxiwsby9_20240331_132207](https://github.com/dartraiden/NVIDIA-patcher/assets/165884208/c50440b5-87af-4fd7-a493-bf4bb53fb210)

Thanks!

**Comment by dartraiden** [comment]
`1DF4` is not blacklisted. only 1D84.
