### ISSUE TITLE
iGPU Intel HD 2500 new drivers is conflicting with the dgpu (P106 90), causing crashes dxgmms1.sys,disabling or downgrading will fix it

### ISSUE THREAD

**Issue by benhur90** [dartraiden/NVIDIA-patcher#108]
Disabling works, but windows will be laggy AF and sometime the game will use the microsoft basic video driver(disabled igpu) instead of the DGPU and downgrading cause same issue as the disabling one  but with a active igpu

**Comment by BluePurplePro** [comment]
P106 works best with Intel Haswell iGPU. You're on your own when using older iGPU than Haswell
