### ISSUE TITLE
NVENC/NVFBC limitations remove

### ISSUE THREAD

**Issue by xrip** [dartraiden/NVIDIA-patcher#11]
I think it will be uber driver if you also remove NVENC limitations on consumer-grade cards with this

https://github.com/keylase/nvidia-patch

Было бы классно, если бы одновременно еще и отключалась проверка на пользовательские видяхи для использования NVENC/NVFBC.

Видел в закрытых ишус подобный вопрос, но у меня на P106-100 и P106-90 прекрасно завелся ваш патч + патч с соседнего гитхаба, и получилась гремучая смесь для сервака - и виде покодировать. и посчитать чтото.

**Comment by dartraiden** [comment]
У меня никогда NVENC не работал, хотя я пробовал патчить.

**Comment by dartraiden** [comment]
А подписывать эти файлы не нужно? Достаточно просто пропатчить?

**Comment by dartraiden** [comment]
Попробуйте.
[nvenc.zip](https://github.com/dartraiden/NVIDIA-patcher/files/12044219/nvenc.zip)

Сначала заменить файлы из [релиза](https://github.com/dartraiden/NVIDIA-patcher/releases/tag/536.40), а поверх уже эти.

**Comment by afx1** [comment]
Попробовал с патченными файлами из nvenc.zip
oCam не видит NVENC
Handbrake позволяет включить, но при попытках энкода через NVENC, выдаёт ошибку.

Так что не работает.
PS: P106-100

**Comment by dartraiden** [comment]
Подождём ответа топикстартера, раз у него это как-то работало.

**Comment by operador777** [comment]
> 1. Unpack [distribution](https://www.nvidia.com/download/driverResults.aspx/210579/) .
> 2. Replace [files](https://github.com/dartraiden/NVIDIA-patcher/releases/tag/536.99) .
> 3. [Additionally, replace these files](https://github.com/dartraiden/NVIDIA-patcher/files/12339920/NVENC_536.99-desktop-win10-win11-64bit-international-dch-whql.zip) with .
> 4. Install as a normal driver via Install.bat
> 
> Post the results.

It fully worked for me, do you have the 537.13  updated version? Thanks a lot

**Comment by dartraiden** [comment]
Where is no patch for 537.13
https://github.com/keylase/nvidia-patch/tree/master/win#windows-10-windows-11-drivers

**Comment by dartraiden** [comment]
Uploaded latest release with patch (NVENC- prefixed package).
