### ISSUE TITLE
Adding Anti-Cheat support?

### ISSUE THREAD

**Issue by BluePurplePro** [dartraiden/NVIDIA-patcher#110]
I've seen Franken Driver implement anti-cheat for their drivers. Is it hard to add anti-cheat support for mining drivers?
https://github.com/arutar/FrankenDriver/issues/6

**Comment by dartraiden** [comment]
They use the same method as NVCleanstall. I tried it, it doesn't work in my case (probably because I patch the binaries and they are only text files).

**Comment by dartraiden** [comment]
As far as I know, we are talking only about one specific anti-cheat, and not about all
