### ISSUE TITLE
Is the NVENC-NvFBC patch no longer necessary?

### ISSUE THREAD

**Issue by operador777** [dartraiden/NVIDIA-patcher#116]
I was looking for the latest version of the NVENC-NvFBC patch for version 555.85, but it is not available, so I decided to patch it myself. When I did, errors occurred and it didn’t work; it seems as if NVIDIA has changed something in the driver. So, I tried testing the functionality of NVENC-NvFBC and realized it is working without any issues or limits even without applying the patch.

![image](https://github.com/dartraiden/NVIDIA-patcher/assets/19232315/7a9809e7-407c-4733-a866-429eda7eb35d)

Is the NVENC-NvFBC patch no longer necessary?
Will this affect graphics cards that do not support NVENC?

I ask because it has worked very well for me, as I have the CMP 40hx, and it has NVENC support. Could any users with other graphics cards without support confirm if they have no issues?

Thank you very much.

**Comment by dartraiden** [comment]
https://github.com/keylase/nvidia-patch/issues/797#issuecomment-2129798896

**Comment by ryuenma** [comment]
Will there be a new update for NVENC-NvFBC ?

**Comment by dartraiden** [comment]
https://github.com/keylase/nvidia-patch/issues/795
