### ISSUE TITLE
Intel HD Graphics 4600 - CODE 12, When P104 is plugged in PCIe slot.

### ISSUE THREAD

**Issue by Matolik01** [dartraiden/NVIDIA-patcher#117]
Hi,
I have Asus B85-Plus with i5-4590.
All drivers are  installed and it work without any problem, until i plug P104 into PCIe. 
Code 12 appeaser in Device Manager at Intel HD Graphics 4600. 
After removing the P104-100 the code 12 disappears, and everything work fine. 

When it shows code 12, it is not possible to play games. Of course the games chop and don't run smoothly.
I managed to run GTA IV but it will run only at medium setting, because it shows in setting only 550MB Video Memory.
Yes, The P104 is set as default, and in GTA IV Benchmark is shows P104-100 as Adapter .

Thank you, for any Help

**Comment by BluePurplePro** [comment]
Go to BIOS settings and set iGFX (onboard graphics) as the first display?

**Comment by Matolik01** [comment]
It is not possible with P104 plugged in, HD 4600 isn't available.

**Comment by Matolik01** [comment]
Only at PhysX, CPU available but it doesn't change anything.

**Comment by Matolik01** [comment]
And Bios is set to iGPU. Of course my P104 has no display connectors, so any other option isn't available.

**Comment by BluePurplePro** [comment]
Definitely Asus fault. If I'm not wrong, some Asus Haswell is tricky to work with P106

**Comment by Matolik01** [comment]
I have also Asus Z270-A with i7-6700 and the P104 work great there. 
But in the  Asus B85-Plus with i5-4590, it is a nightmare. I tried bunch of different drivers and reinstalled the system 4 or 5 times, but noting helps at all.  
It just keeps refusing to communicate with the display adapter.

**Comment by BluePurplePro** [comment]
https://linustechtips.com/topic/1001580-p106-now-support-directx-not-official/?do=findComment&comment=12566612
![Untitled](https://github.com/dartraiden/NVIDIA-patcher/assets/84092284/90bbf835-34aa-48ef-b416-a47784916409)
Because of Asus Haswell

**Comment by Matolik01** [comment]
That's sad. 
Thank you for your time and clarification of the situation.

**Comment by Matolik01** [comment]
Don't buy Asus Haswell

**Comment by Hasbkv** [comment]
Hey, I have the same exact settup!

What you need to do is turn off that CSM (Disable CSM).
