### ISSUE TITLE
Spoof GPU name

### ISSUE THREAD

**Issue by BrainlessGuy** [dartraiden/NVIDIA-patcher#118]
Hello Dartraiden. Thanks for your work. Could you tell me how can I change GPU name? When I run "setup.exe" the standard installer opens and I can't do it.

**Comment by operador777** [comment]
Hello, for the GPU spoof, change the installation mode from "Express" to "Custom"
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/19232315/e42e22be-704f-4400-be00-90f25fb6d42f)

Then, check the "Spoof GPU" box and click continue to proceed with the installation:
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/19232315/f2f2c264-f321-4338-9bfb-b9c5b5e8e7cb)

And with that, it should work for you without any problem.

**Comment by daltroaugusto** [comment]
For some reason it never worked for me, in any version of the driver.

![image](https://github.com/dartraiden/NVIDIA-patcher/assets/58415152/35c85cd5-00c1-4874-a1a0-3b576a3f4868)

**Comment by dartraiden** [comment]
Try the latest release, I found and fixed a bug that prevented this option from working.
