### ISSUE TITLE
I dont know how to message directly, but I have a question.

### ISSUE THREAD

**Issue by madobenanamixD** [dartraiden/NVIDIA-patcher#12]
- I heard someone said that this patcher didnt work on 70HX. Is it true?
- Btw, if this thing can be the 3070ti, may the PCI-E X4 convert to X16? 
Thank you so much!

**Comment by dartraiden** [comment]
1) Can't test, I don't own CMP cards
2) Nope, it's hardware limited. Therefore, CMP-cards are unsuitable for games, PCI-E 1.0 x4 drops performance very much.
