### ISSUE TITLE
556.12-update1 bugs with p106-090

### ISSUE THREAD

**Issue by igorjos** [dartraiden/NVIDIA-patcher#123]
Hi I have Intel 630 and P106-090.

When I run the installation, drivers are installed correctly, the card name is changed to Gtx 1060, but the card details are missing:
Card CPU data, Card memory data etc.
Only temperature data are returned back.
Nvidia-smi is not working, and occasionally windows (10) disables the card by itself with error code 43.

I have:
- Asrock h110 pro btc +
- 16GB 2400Mhz ram
- Integrated Intel 630 + Mining P106-090
- core i5 7400
- 500 W PSU

P106-090 is  tested on pcie x16 on board directly and with riser 1x-16x the same outcome.

Is there anything I can do as a workaround or maybe the card is dead?

Thanks

**Comment by dartraiden** [comment]
This usually happens when the driver is not patched. Make sure that the old driver is removed using DDU and at this time Windows does not have access to the Internet (until the new driver is installed)

Just in case, I reuploaded the driver, try it.

**Comment by aleksandraleksandrov666666** [comment]
В такой конфигурации работает идеально

**Comment by igorjos** [comment]
Hi,

I followed your comments,
I have re-downloaded the drivers again.
Restored BIOS to default.
Reinstalled windows from scratch and turned the internet off.
Installed the drivers as per the instructions:

Here is the result:

Right after install, the gpu is recognized but has error 43 so not used.

![IMG_7918](https://github.com/dartraiden/NVIDIA-patcher/assets/5036808/47c3b50b-179c-422a-9d84-d21d1ef1e5aa)

Then I had restarted the PC and disabled the GPU in the device manager and restarted the PC again.

Error not there anymore but IRQ error is present.
![IMG_7919](https://github.com/dartraiden/NVIDIA-patcher/assets/5036808/ae529d23-ed5f-4a5d-820e-b872b7dfdc3e)

End result the GPU is not working
![IMG_7920](https://github.com/dartraiden/NVIDIA-patcher/assets/5036808/99ccc744-3016-42a7-8362-7828e7080c86)

**Comment by aleksandraleksandrov666666** [comment]
Дополнительное питание видеокарты посмотри

**Comment by igorjos** [comment]
@aleksandraleksandrov666666 I have a 650W power supply, while the system in total (including the GPU) uses less than 350W. So adding additional power supply seems as really not needed.

**Comment by aleksandraleksandrov666666** [comment]
6pin

**Comment by dartraiden** [comment]
To make sure that the problem is not in the driver
* try [https://disk.yandex.ru/d/5LO4wqy177XZyw](some old driver) (526.86 for example)
* [try the official 417.22 driver](https://www.youtube.com/watch?v=w3PHWJWlXgo)

**Comment by igorjos** [comment]
So apparently this is some issue with the card itself.
None of the drivers work, I had tried all suggestions you had mentioned. As well the card is connected to 6pin PCIe power all the time.

I don’t need the card for mining, I need it for CUDA so the error 43 would not help, therefore I will close this issue. Hopefully it will be used to others before they buy the card - not to do it, because drivers are not working
