### ISSUE TITLE
Got a virus in my OpenGL install location

### ISSUE THREAD

**Issue by Hufi25** [dartraiden/NVIDIA-patcher#125]
Firstly I'm not trying to make any accusations. I'm just trying to get everything fixed.

Yesterday when I tried playing Minecraft I got an error relating to the OpenGL driver. Turns out 2 days ago Windows fount "Wacatac" in the location of nvoglv32.dll  and disabled it.

I'm presuming it just placed itself here, because I haven't had any issues previously.

I'm not an expert and I wanted to ask is this a correct or false detection and, should I just reinstall the driver? (after running malwarebytes etc)

**Comment by dartraiden** [comment]
False detection
Add folder to exceptions in AV settings.

**Comment by Hufi25** [comment]
Thank you for the quick response it works again (: 👍
