### ISSUE TITLE
Fake names

### ISSUE THREAD

**Issue by BrainlessGuy** [dartraiden/NVIDIA-patcher#127]
An error occurs when changing the name

**Comment by dartraiden** [comment]
If you don't enable this option, is everything OK?

**Comment by BrainlessGuy** [comment]
Yep

**Comment by dartraiden** [comment]
Can you plese try some old driver?
For example https://disk.yandex.ru/d/J41kbcTMdBNrzA

**Comment by BrainlessGuy** [comment]
I tried installing several previous versions, but they only work if I don't change the name. 
A week or two ago I installed the latest driver version for a friend at that time, everything worked

**Comment by dartraiden** [comment]
0_0

Maybe AV software eats some files?

**Comment by dartraiden** [comment]
"Fake names" removed. All GPU's now have "gaming" names.
