### ISSUE TITLE
The 40HX paired with the GTX 670 problem. 

### ISSUE THREAD

**Issue by osposob** [dartraiden/NVIDIA-patcher#130]
There is no 40HX in the application settings in the graphics settings and 40HX is not used when launching applications and games. BUT in the game "Generation Zero" both accelerators are used in some way, there is no such thing anywhere else. Driver 472.12 + patch, Windows Pro 10 22H2 build 19045.4651, AMD Ryzen 5 1600 on ASUS PRIME B350 PLUS, 40HX in the main slot, GTX 670 in the additional. Everything is in the devices, GPU-Z is fine, in the nvidia panel in the settings of the CUDA and OpenGL parameters you can choose between 40HX and GTX 670, but this does not give anything - everything works on GTX 670. I used every tambourine I found. "Generation Zero" began to fly na ultrah.

**Comment by osposob** [comment]
Если удалить драйвера GTX 670, то в играх начинает использоваться 40HX, но с жуткими тормозами.

**Comment by osposob** [comment]
> There is no 40HX in the application settings in the graphics settings and 40HX is not used when launching applications and games. BUT in the game "Generation Zero" both accelerators are used in some way, there is no such thing anywhere else. Driver 472.12 + patch, Windows Pro 10 22H2 build 19045.4651, AMD Ryzen 5 1600 on ASUS PRIME B350 PLUS, 40HX in the main slot, GTX 670 in the additional. Everything is in the devices, GPU-Z is fine, in the nvidia panel in the settings of the CUDA and OpenGL parameters you can choose between 40HX and GTX 670, but this does not give anything - everything works on GTX 670. I used every tambourine I found. "Generation Zero" began to fly na ultrah.

https://github.com/dartraiden/NVIDIA-patcher/issues/57#issuecomment-1783902161

**Comment by dartraiden** [comment]
Try to set `EnableMsHybrid = 1` for one GPU and `EnableMsHybrid = 2` for another.

**Comment by osposob** [comment]
Thanks! A similar discussion is here https://github.com/dartraiden/NVIDIA-patcher/issues/57
