### ISSUE TITLE
How to shut off "Spoof/Change name" if I dumb like Magic Carp

### ISSUE THREAD

**Issue by ByWallkroft** [dartraiden/NVIDIA-patcher#137]
I'm rly dumb and don't know how turn off changing the name of GPU in 560.70 driver. 
In manual I read so I can change this setting during install process, but I have not this option in my driver. 
I got some troubles with my P106-100 whose name changing to GTX1060-6G after driver installation. For what reason I can't play the games with Riot Vanguard anti-cheat. I hope, that the reason of this problem
I know, my English isn't good, so if You need it a can repeat that post at russian

**Comment by ByWallkroft** [comment]
UPD:  I need a patched driver with the original name for the P106-100. Can you send link o patch name to driver?

**Comment by dartraiden** [comment]
This option caused problems and was removed.

1) `bcdedit -set TESTSIGNING ON`

Reboot.

2) Open nvaci.inf, find `ID_10DE.1C07.0001.0002 = "NVIDIA GeForce GTX 1060"`, change as you want.

3) Install driver

4) `bcdedit -set TESTSIGNING OFF`

Reboot

**Comment by dartraiden** [comment]
> Can I turn on shadowplay on P106-100?

No idea, I do not use ShadowPlay at all...

**Comment by dartraiden** [comment]
> I hope, that the reason of this problem

Nope, probably the reason is "Anticheat does not like Atheros digital signature".

**Comment by ByWallkroft** [comment]
> > I hope, that the reason of this problem
> 
> Nope, probably the reason is "Anticheat does not like Atheros digital signature".

Have you got any ideas, how fix it? Because I saw some vids on Youtube, where some people played at P106-100 at Valorant/League of Legends, but there no good instructions and all at Turkish language.
So about ShadowPlay. Can at be a bug at 560.70 driver at current model of GPU? Asus P106-100. I send full model name of my GPU about 48hours. I hope, I do it faster. Just after try some another driver versions ofc.

**Comment by dartraiden** [comment]
> Have you got any ideas, how fix it?

Buy a certificate to sign the driver (it costs several hundred dollars). After some time it will be banned, buy another certificate...

Seriously, I have no way to fight anti-cheats.

**Comment by dartraiden** [comment]
> So about ShadowPlay.

Perhaps something has changed in new versions of Shadowplay and the old method no longer works.

**Comment by operador777** [comment]
> UPD: I need a patched driver with the original name for the P106-100. Can you send link o patch name to driver? And 2nd question: Can I turn on shadowplay on P106-100? Because the method from the instructions does not work on my PC

Another alternative to shadowplay is to use "Nvidia app", it is new, still under development but has most of the features of Shadowplay and works with any video card (I was able to test it on a CMP 40hx and a couple of others).

**Comment by dartraiden** [comment]
> Nvidia app

Added to readme, thanks

**Comment by ByWallkroft** [comment]
> > Nvidia app
> 
> Added to readme, thanks

Thank you. I tried all versions of all drivers. Tried delete all sertificates. Problem in damn Riot Vanguard. 
Thank for your answers

**Comment by dartraiden** [comment]
The only option is using 417.22 with registry hack.
