### ISSUE TITLE
"NVIDIA-patcher-master.zip" error problem.

### ISSUE THREAD

**Issue by wonheui** [dartraiden/NVIDIA-patcher#14]
When patching with the previously provided "NVIDIA-patcher-master.zip", an error occurs as shown in the figure below.
I ran the patch on Windows 10 PRO.
I would appreciate it if you could tell me how to solve it.
![화면 캡처 2023-07-26 030210](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/6926fa00-731a-4dcd-a21d-43e7a5cd88c8)
![화면 캡처 2023-07-26 031147](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/438d3218-b9de-485b-b125-a9aa67eac16e)

**Comment by dartraiden** [comment]
Anyway it does not work anymore because http://tsa.pki.jemmylovejenny.tk is down.

**Comment by dartraiden** [comment]
Fixed in https://github.com/dartraiden/NVIDIA-patcher/commit/5792ccc5efc7e4a033c5ec3f6c3e8642daee5112

But due to certificate blocking, patcher still does not work. Use [releases](https://github.com/dartraiden/NVIDIA-patcher/releases) instead.

**Comment by wonheui** [comment]
Dear dartraiden...
Thank you very much.~~
i love you.~~~🥰😘🤗
