### ISSUE TITLE
About the InstallCert folder

### ISSUE THREAD

**Issue by kaishi961125** [dartraiden/NVIDIA-patcher#144]
Just put the certificate file in this folder and it will be OK. Do you need to install it manually?

![image](https://github.com/user-attachments/assets/d9e89b96-901f-4ba3-96bb-8bb88582fa4e)
![image](https://github.com/user-attachments/assets/c09e089f-9cea-4d5d-b00e-2be761111b65)

**Comment by dartraiden** [comment]
Certs will be installed automatically by InstallCert.nvi
