### ISSUE TITLE
Don't Update to 536.67 version?

### ISSUE THREAD

**Issue by HoangNghi** [dartraiden/NVIDIA-patcher#15]
Don't Update to 536.67 version?

**Comment by afx1** [comment]
My experience with 536.67 patch:

1) The new installation method via "Setup.exe" installs the usual mining driver (in my case P106-100). It can't be selected for performance mode.

2) With the old, manual installation method via Device Manager, the 1060 6G is installed without problems, but you can't select it for performance mode either.

EnableMsHybrid is enabled in registry.

The old patch for 536.40 works without problems.
Windows 10 22H2 (19045.3324)

-----

1) По новому методу установки через "Setup.exe" устанавливается обычный майнерский драйвер (в моем случае P106-100). При этом нельзя его выбрать для режима производительности, соответственно и игр/софта.

2) При старом, ручном методе установки через Диспетчер устройств, 1060 6G ставится без проблем, но тоже нельзя выбрать для режима производительности.

EnableMsHybrid прописан в реестре.

Старый патч для 536.40 работает без проблем.
Windows 10 22H2 (19045.3324)

**Comment by dartraiden** [comment]
Okay, tomorrow I'll try to test it on my P106-100

**Comment by dartraiden** [comment]
@afx1 я что-то совсем ничего не понимаю. Воткнул карту, ставлю свой драйвер с выбором руками 1060 - ошибка 43.
Если добавить AdapterType = 2 (этот ключ переводит карту из 3D-режима в вычислительный), то ошибки нет. Т.е. полное впечатление, что драйвер я ставлю непропатченный (патч как раз и убирает ограничение, не позволяющее переводить майнинговую карту в 3D-режим), но я его пропатчил своими руками.

Либо как-то сказывается, что у меня основной картой стоит Радеон (нет возможности его убрать), либо то, что Windows 11 (не очень хочется сносить и ставить 10)

В общем, мне нужен доброволец, которому бы я кидал различные версии драйвера, а он бы отписывался о результатах. Если ты готов таким добровольцем быть, дай какой-нибудь способ связи (мессенджер, вк, вот это всё)

**Comment by maslomeister** [comment]
Please add 536.40 patch to releases while you are trying to figure out what's wrong with 536.67

**Comment by afx1** [comment]
@dartraiden 
В Discord "@fox_cp".
Ближайшие пару дней как раз будет много свободного времени.

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/releases/tag/536.99
