### ISSUE TITLE
Pcie speed change inquiry...

### ISSUE THREAD

**Issue by wonheui** [dartraiden/NVIDIA-patcher#16]
Dear dartraiden... Hello...
I recently bought a used "P102-100".
The uploaded file was successfully recognized as "GTX 1080 TI".
I am always grateful to dartraiden.

However, I have a question for you.
As pictured below...
For "P102-100" the PCIe speed is set to x4 not x16.
Is there a way to change the pcie speed to x16?
Please respectfully.

![화면 캡처 2023-08-13 230838](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/12a22ebd-9d8f-4737-b365-5b47e1f270ed)

**Comment by dartraiden** [comment]
[illario](https://boosty.to/illario) tried to bypass this limitationand came to the conclusion that this limitation is at the hardware level.

**Comment by wonheui** [comment]
Oh, I see...
Thank you for answer.~^^
