### ISSUE TITLE
PCIE 30HX

### ISSUE THREAD

**Issue by Medsinso** [dartraiden/NVIDIA-patcher#162]
Good morning, I have a Gigabyte CMP 30HX and I would like to unlock the PCIe lanes, but I don’t know what I need to solder. It seems they are 230 NF capacitors, but I’m not sure if those are the ones. If anyone has done this successfully, it would help me a lot. Thanks in advance.

**Comment by 0su-gh0ul** [comment]
type 0402, 0,22 MF, 50V
