### ISSUE TITLE
Virus warning by Windows Defender

### ISSUE THREAD

**Issue by SirDebugALot** [dartraiden/NVIDIA-patcher#173]
The following file is deemed Trojan:Win32/Wacatac.B!ml

NVENC-NvFBC-565.90-desktop-win10-win11-64bit-international-dch-whql\Display.Driver\nvoglv64.dll

What is going on?

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/issues?q=is%3Aissue+is%3Aclosed+virus
