### ISSUE TITLE
Please update patched driver to 475.14

### ISSUE THREAD

**Issue by tarkh** [dartraiden/NVIDIA-patcher#174]
Nvidia recently updated legacy driver to 475.14
https://www.nvidia.com/ru-ru/drivers/details/229833/

Please, can you update patched installer from 472.12 to new 475.14
Thank you!

**Comment by dartraiden** [comment]
Mining card support has been removed from this driver

**Comment by tarkh** [comment]
Thanks!
Btw, tried driver from [link](https://pan.huang1111.cn/s/7GqEHg?path=%2F2%E5%8F%AF%E8%83%BD%E6%9C%89%E7%94%A8%E7%9A%84%E5%85%B6%E4%BB%96%E9%A9%B1%E5%8A%A8%2F6xx%E7%B3%BB%E5%8F%8CN%E5%8D%A1%E5%BC%80%E6%99%AE%E5%8B%92%E4%B8%93%E7%94%A8%E9%A9%B1%E5%8A%A8) you've posted in other issue. And probably it works :)

Just edited RegEdit and set
1. On my gt 730 - EnableMsHybrid = 2
2. On my p106-100 - EnableMsHybrid = 1, AdapterType = 4

Then in Nvidia panel select Performance card for all and p106 in PhysX
Haven't tried anticheats games yet, but in BeamNG and Minecraft Java all works fine.

**Comment by dartraiden** [comment]
Yes they add support for mining cards in .inf

**Comment by tarkh** [comment]
> Is this really necessary?

Really idk ) This parameter comes from my previous settings, so can't say for sure is it necessary, will try without it later. But `EnableMsHybrid = 2` on display card and `EnableMsHybrid = 1` on p106 do matters, because without them dropdown field in Nvidia panels adapter selection is empty.

**Comment by tarkh** [comment]
> Is this really necessary?

Tested, everything works the same way with `AdapterType = 1`.
Thanx! Closing issue.
