### ISSUE TITLE
Troyan in patch

### ISSUE THREAD

**Issue by maofuentes** [dartraiden/NVIDIA-patcher#175]
Good day please remove troyan virus in the dlls, i only have pc with windows for use games, and install this patch and few days ago login in my microsoft account

Actividad de inicio de sesión inusual
Hemos detectado algo inusual sobre un reciente inicio de sesión de la cuenta Microsoft [mf**a@gmail.com](mailto:mf**a@gmail.com).
Detalles de inicio de sesión
País o región: Armenia
Dirección IP: 217.113.31.149
Fecha: 18/10/2024 21:52 (GMT)
Plataforma: Windows
Explorador: Chrome

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/issues?q=is%3Aissue+is%3Aclosed+virus

False positive.

the fact that someone else logged into your account has nothing to do with patch
