### ISSUE TITLE
problems with NVENC

### ISSUE THREAD

**Issue by Clubmaster736** [dartraiden/NVIDIA-patcher#176]
Hello, such a disaster. I have a p106-100 from GIGABYTE for 6 Gb rev 1.0, according to tech. according to the characteristics, it should be started in NVENC, but not like this. after reading the specifications on techpowerup, I found the following lines: 
NVENC: 6th Gen
NVDEC: 3rd Gen
PureVideo HD: VP8
VDPAU: Feature Set H. 
that is, she should get involved with him, but she doesn't want to. I installed new drivers with a patch on NVENC, but it did not work. maybe the problem is in the patch or just some kind of physical limitation on working with NVENC?

**Comment by rvrdx** [comment]
All the mining cards have disabled nvenc except for CMP 40HX for some reason. If the nvenc patch didn't work that means your card does'nt have working nvenc.

**Comment by dartraiden** [comment]
According to my tests NVENC is disabled on P106 (presumably hardware)
