### ISSUE TITLE
dont work battlefield 1 and battlefield 5 p106 -100

### ISSUE THREAD

**Issue by XxtionaxX** [dartraiden/NVIDIA-patcher#178]
my p106 -100 dont work  battlefield 1 and battlefield 5 driver version 565.90
![Screenshot 2024-10-26 183842](https://github.com/user-attachments/assets/53b2ce76-ac5c-4a5f-99bf-bca619a7e0e7)
![Screenshot 2024-10-26 183915](https://github.com/user-attachments/assets/d5aff3a8-9837-4ef0-8556-d6c88a99f95e)
I think it's because of the anti-cheat, can anyone help me how to get around this? I launch games with p 106-100 dont integrated graphics

**Comment by dartraiden** [comment]
Та же проблема с античитом EAC, что в https://github.com/dartraiden/NVIDIA-patcher/issues/66 и https://github.com/dartraiden/NVIDIA-patcher/issues/103

**Comment by astronautduckpc** [comment]
> Hi, I was finally able to run battlefield 1 and battlefield 5 on p106 -100, only on this driver. Installation method 1. Hurray, I'm very happy, thanks to the developers of this driver. https://raincandy.tech/nvcmpgpu/
Какую версию драйвера Вы используете? Можете оставить ссылку на драйвер через google disk ?
