### ISSUE TITLE
p 102 100 не робіт

### ISSUE THREAD

**Issue by JohannesbekbulatXia** [dartraiden/NVIDIA-patcher#179]
Них*я не встают эти ваши блин драйвера на карту как надо, видеокарта живёт своей жизнью, отображается на компе, но ей на меня насрать как и в принципе всем кукушкам на своих птенцов. 
Проблема
1. Не отображается интерфейс, через которых подключена карта
2. Если ставить насильно драйвера 1080, то интерфейс отображается
3. Если ничего не делать или делать что-то из этого, то один член мужской, карта живёт своей жизнью.

**Comment by dartraiden** [comment]
Попробуйте драйвер от китайцев
https://github.com/dartraiden/NVIDIA-patcher/issues/140

**Comment by dartraiden** [comment]
Всё это, конечно, здорово, но у меня
1) нет нескольких сотен долларов в год на покупку сертификата для подпись дров
2) нет возможности купить его из России

**Comment by JohannesbekbulatXia** [comment]
Так монетизируй свой проект, как делают все остальные. Мне не лень отдавать 5 баксов в год за то, что ты делаешь. В РФии, как ты утверждаешь, под санкциями все сложно достать, но в такие трудные времена необходимы лучшие умы.
