### ISSUE TITLE
Lock 100 fps on P 104-100

### ISSUE THREAD

**Issue by nRiHa** [dartraiden/NVIDIA-patcher#18]
Столкнулся с проблемой того, что ни одна игра не выдаёт выше 100 фпс на этой карте. Можете назвать причину? 

Нет конечно я понимаю что узкая шина и т.д. и т.п., но что-то я сомневаюсь что дело в этом

**Comment by dartraiden** [comment]
Кроме тупых предположений типа "монитор больше 100 Гц не может" - идей нет.
