### ISSUE TITLE
Windows 10 x64 reports trojan virus in driver

### ISSUE THREAD

**Issue by mcfixstuff** [dartraiden/NVIDIA-patcher#181]
Trojan:Script/Wacatac.B!ml in file
file: C:\Windows\System32\DriverStore\FileRepository\nvddi.inf_amd64_6b0ab0a43cab35f6\nvd3dumx.dll

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/issues?q=is%3Aissue+is%3Aclosed+virus
