### ISSUE TITLE
RTX 3060 3840SP

### ISSUE THREAD

**Issue by ByWallkroft** [dartraiden/NVIDIA-patcher#182]
Драйвер отказывается устанавливаться (неподдерживаемое оборудование) с картой MLLSE 3060M 12Gb
Rain Candy не работает нормально, Franken крашится( Прошу помощи

**Comment by dartraiden** [comment]
> Драйвер отказывается устанавливаться (неподдерживаемое оборудование)

Логично, я поддержку мутантов не реализовывал и не хочу.

> Franken крашится

Лучше спрашивать у автора.

**Comment by ByWallkroft** [comment]
> > Драйвер отказывается устанавливаться (неподдерживаемое оборудование)
> 
> Логично, я поддержку мутантов не реализовывал и не хочу.
> 
> > Franken крашится
> 
> Лучше спрашивать у [автора](https://github.com/arutar/FrankenDriver/issues). Он по-любому понимает в мутантах больше меня (это одна из причин, почему я не хочу в это лезть).
> 
> Ткнув пальцем в небо, я бы сказал, что, возможно, карта неисправна. MODS/MATS в помощь (или чем там тестируют карты)

Просто в описании драйвера увидел 3060 3840sp, по сему спросил. 
Пальцем в небо вы абсолютно верно попали. По всё симптоматике - ошибки по памяти
