### ISSUE TITLE
Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by Pustartm** [dartraiden/NVIDIA-patcher#187]
Hi, Windows Defender identifies the Trojan virus:Script/Waratah.H!ml in the patch files. Why is this happening?

![13514ea7-2bc0-4111-b5c3-4a14c426e888](https://github.com/user-attachments/assets/3b483850-81f8-45e0-be34-6560bbad37ef)

**Comment by dartraiden** [comment]
False positive.
