### ISSUE TITLE
last 566.14 NVIDIA patched drivers

### ISSUE THREAD

**Issue by HuntIce** [dartraiden/NVIDIA-patcher#188]
Windows Defender finds a Trojan:Script/Wacatac.B!ml in the archive 566.14-desktop-win10-win11-64bit-international-dch-whql.zip

Am I the only one experiencing this or has anyone encountered this?

this was not the case in version 537.13

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/issues/181#issuecomment-2446768431

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/commit/8548e3c77ce41d67ce67159942b711e7c8d741fc
