### ISSUE TITLE
CMP 40 hx

### ISSUE THREAD

**Issue by Basileus2** [dartraiden/NVIDIA-patcher#19]
Привет, может кто знает, инсталирую цифросертификат, но в nv_disp пишет что сертифікат Edgardo Roberto Viera недествительный, он с 2012 до 2013, сертификат fake timestamp responder есть, цифровая подпись на драйвере отсутсвует

**Comment by dartraiden** [comment]
Если ставилось через Install.bat, то это нормально, он в конце удаляет сертификат из системы.

**Comment by Basileus2** [comment]
Ок, а нужно ли запускать install.bat перед ручной установкой драйвера, и можно ли вывести изображение на другую дискретную карточку, если можно то как?

**Comment by dartraiden** [comment]
Ручная установка больше не нужна.
Совместная работа двух дискреток зависит от собственно той дискретки, котоаря будет выводить изображение. Чем старее, тем меньше шансов. У современных карточек нет проблем.
