### ISSUE TITLE
The new driver version

### ISSUE THREAD

**Issue by FearRaven11** [dartraiden/NVIDIA-patcher#195]
I think there is some kind of bug because when i am trying to launch the setup.exe it says a error has occured if anyone can confirm if it’s happening with them or just me please and thank you

**Comment by dartraiden** [comment]
Typo in setup.cfg
Fixed, thanks

**Comment by quoctrieunguyen22** [comment]
> Typo in setup.cfg Fixed, thanks

where is that typo
