### ISSUE TITLE
CMP 70HX seems to not be working

### ISSUE THREAD

**Issue by Emil280** [dartraiden/NVIDIA-patcher#2]
I tried to use this driver mod with a CMP 70HX but it seems that it isn't working at least the latest drivers. It fails to pick up the details of the card correctly in GPU-z after installing the driver with some information being missing or incorrect.

**Comment by dartraiden** [comment]
Can you upload the Display.Driver folder (after applying the patch) to some file sharing service?

**Comment by Emil280** [comment]
I have already returned the CMP 70HX because the specs weren't what was listed on techpowerup and no modded driver worked for it. The specs of the CMP 70HX don't fully match any mainstream geforce gpu so I'm not sure if it is possible to even get it to run games with modded drivers. Also after testing it in geekbench since cuda was enabled with official nvidia driver I got a score of around 50k in cuda so i don't know if it's even worth while modding the drivers for the cmp 70hx. I will close this issue since I no longer have the CMP 70HX and therefore cannot test wether any additional driver modifications would get it to run games.

**Comment by dartraiden** [comment]
> I'm not sure if it is possible to even get it to run games with modded drivers.

Theoretically possible, but the inf files would also have to be modified.

It is probably better to remove support for CMP cards from the patcher, since most of them have a limited bus width and, as a result, very low gaming performance
