### ISSUE TITLE
"Exploring a Modified NVFlash: Potential Solution for Mining Cards? A Look at the Patched NVFlash Bypassing Nvidia Security Signatures"

### ISSUE THREAD

**Issue by systemdrhnid** [dartraiden/NVIDIA-patcher#20]
**[Question]** I've come across a modified NVFlash tool that essentially bypasses the Nvidia security signature processor, allowing it to flash any BIOS onto any graphics card, albeit with certain conditions. Could this potentially serve as a solution for mining-oriented graphics cards? Here's the link to the discussion: [OMG-VFlash: Fully Patched NVFlash from X to Ada Lovelace](https://www.techpowerup.com/forums/threads/omg-vflash-fully-patched-nvflash-from-x-to-ada-lovelace-v5-780.312601/) (Thread #312601) on TechPowerUp forums. https://github.com/notfromstatefarm/nvflashk

**Comment by dartraiden** [comment]
You could flash any bios into any card a hardware programmer. It won't work.

**Comment by dartraiden** [comment]
```
Error Code = 0x0000005A(90): NV_UCODE_ERR_CODE_DEVID_MATCH_LIST_DEVID_MATCH_FAILED
Device ID in the rom image does not match the device ID in the chip.
Update aborted, please use a rom image that supports device ID 0x1C07.

Falcon CLOSE
```
