### ISSUE TITLE
537.13 driver not working CMP 40HX

### ISSUE THREAD

**Issue by operador777** [dartraiden/NVIDIA-patcher#22]
The recent version of the driver doesn't work with the CMP 40HX; it was installed correctly according to the given instructions. GPU-Z doesn't display information accurately, and the values are shown as 0. This was resolved by installing the previous version, 536.99 wich is working perfectly.

**Comment by dartraiden** [comment]
Please show Device ID of your card 

Use PowerShell comman `Get-CimInstance Win32_PnPEntity | where caption -match 'CMP 40X'` where CMP 40X is the name of your card from Device Manager.

**Comment by operador777** [comment]
> Please show me Device ID of your card
> 
> Use PowerShell command `Get-CimInstance Win32_PnPEntity | where caption -match 'CMP 40HX' | select -Property DeviceID` where CMP 40HX is the name of your card from Device Manager.

Offcourse, there is= PCI\VEN_10DE&DEV_1F0B&SUBSYS_88041043&REV_A1\4&35926DA&0&0008

**Comment by dartraiden** [comment]
Ah, I made a typo in the patcher code. I fixed a bug in the public version of the patcher (which doesn't work due to a banned certificate), but didn't fix it in the private copy that I use to sign releases.

**Comment by operador777** [comment]
Tomorrow I will try. Thank you for everything you do for us.

**Comment by dartraiden** [comment]
Is there a real need for this? I haven't seen a game that refuses to work. This is just a text string, it does not affect the software. Moreover,  software such as Geforce Experience still detects the card with its real name.

**Comment by operador777** [comment]
It was happening to me with an old Battlefield game, but I fixed it using Regedit. Thank you very much.

**Comment by operador777** [comment]
> Ah, I made a typo in the patcher code. I fixed a bug in the public version of the patcher (which doesn't work due to a banned certificate) but didn't fix it in the private copy that I use to sign releases. As a result, the patch for PXXX cards worked, but the patch for CMP XX cards did not.
> 
> Tomorrow everything will be done.

Issue solved, I just installed the corrected version 537.13 and it works perfectly. Thank you very much.

![image](https://github.com/dartraiden/NVIDIA-patcher/assets/19232315/150af49a-86f3-4a7d-8e85-60ac359c9955)

**Comment by Fabeloz** [comment]
Tell me , are there fixes for linux , or after driver 470 , the drivers above are limited ..

**Comment by dartraiden** [comment]
I do not use Linux at all, so no idea.
