### ISSUE TITLE
it can be support device 2205 ??

### ISSUE THREAD

**Issue by hxzpily2** [dartraiden/NVIDIA-patcher#23]
3080TI 20G

deviceid 2205

is  there any possibility of support ??

**Comment by hxzpily2** [comment]
> Interesting...
> 
> Is there already a driver for these cards? (official or made by someone)

this is a testing driver  516.59  have deviceId 2205  

https://www.aliyundrive.com/s/Bi1i5xbSLxq

widows10 must be in testing mode can install it

use powershell      bcdedit /set testsigning on

**Comment by hxzpily2** [comment]
wait 30 minute  i upload dropmefiles  

> I cannot register on aliyundrive.com, the website does not accept Russian phone numbers. Can you reupload driver on some file-transfer hosting like dropmefiles.com or baidu.com?

this is another driver  use the same CA file  

its  not need to enter  windows  testing mode 

unzip file ，first install   “”firstinstall folder“” files ，and then turn off wifi  and install the driver use setup.exe

url：https://pan.baidu.com/s/1whmpzLCJXqs0As_YGxVXEA?pwd=89ic 
password：89ic  


if  windows10 install  update  KB5028182 ，it not be used

**Comment by hxzpily2** [comment]
https://dropmefiles.com/E7P6v

**Comment by WHUT666** [comment]
cool！

**Comment by hxzpily2** [comment]
> Actually, it is driver 516.**61**
> 
> The bad news is that I didn't find the original driver so I could not compare the files. Only 516.61 OEM Lenovo driver, but it is not suitable for this purpose.
> 
> So we have two options:
> 
> 1. What if you install the [official driver](https://www.nvidia.com/download/driverResults.aspx/210648/en-us/) manually through the task manager, uncheck "show only compatible devices" and select 3080 from the device list?
> 2. I can sign this Chinese modded driver so it will work.


thanks a lot 

options 1   I use the official driver  only  cuda can use    

                  but is install your patcher driver 536.67  select 3080 from device list   

                 furmark can work ,beacuse it runing in opengl ,and cuda can work  ,only directX not work 

                the gpu-z image []( https://dropmefiles.com/rZTjP ) 

option 2   I don't quite understand  ，it is means sign  516.67 ？

**Comment by dartraiden** [comment]
I will sign https://dropmefiles.com/E7P6v

**Comment by hxzpily2** [comment]
another  driver is 516.59 and must use  in  windows testing  mode  

if it can  provide some assistance ，i can upload on  dropmefiles

**Comment by dartraiden** [comment]
Yes it can help.

**Comment by WHUT666** [comment]
> Yes it can help.

https://dropmefiles.com/w08JI

**Comment by WHUT666** [comment]
С нетерпением ждем последней версии графического драйвера rtx3080ti 20g

**Comment by WHUT666** [comment]
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/38042728/3b69d77d-7572-4512-a01b-118d840a012f)

**Comment by WHUT666** [comment]
Ура!

**Comment by dartraiden** [comment]
![Безымянный](https://github.com/dartraiden/NVIDIA-patcher/assets/5046855/bfa571ba-85f4-469d-b768-d1e1ea114db3)

Unfortunately this is also 516.61

**Comment by dartraiden** [comment]
[nv_disp.zip](https://github.com/dartraiden/NVIDIA-patcher/files/12438435/nv_disp.zip)

**Comment by hxzpily2** [comment]
> wontfix

https://dropmefiles.com/fpl3x      this is 516.59

**Comment by dartraiden** [comment]
This is exactly same file as https://www.nvidia.com/download/driverResults.aspx/190568/ru/

**Comment by dartraiden** [comment]
Uploaded to [releases](https://github.com/dartraiden/NVIDIA-patcher/releases/tag/516.61).

**Comment by hxzpily2** [comment]
> Uploaded to [releases](https://github.com/dartraiden/NVIDIA-patcher/releases/tag/516.61).

 Спасибо за работу.

**Comment by WHUT666** [comment]
Can the name of the graphics card be changed? In the NVIDIA Control Panel, the name of this graphics card is ‘NVIDIA Graphics Device’ instead of ’NVIDIA GeForce RTX 3080ti‘, which will cause some games to not recognize the graphics card.

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/issues/22#issuecomment-1692451348

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/issues/49#issuecomment-2189967971
