### ISSUE TITLE
Is it safe to ignore the  Trojan.Heur!.00252033 report?

### ISSUE THREAD

**Issue by link89** [dartraiden/NVIDIA-patcher#24]
The report show that the following file contain trojan? Is it safe to use this patch?

https://www.virustotal.com/gui/file/9b10b58a01761837911d11ee5370d4b6cad693096cf19b42d2638a940b0d274d?nocache=1

**Comment by dartraiden** [comment]
You can take the original nvlddmkm.sys and compare it byte by byte with the patched one.
