### ISSUE TITLE
GT710 becomes Microsoft Basic Render Driver after install the latest patcher

### ISSUE THREAD

**Issue by link89** [dartraiden/NVIDIA-patcher#25]
After installing the Nvidia driver with latest patcher, my P106-6G card gets the 3D support. But my GT710 driver becomes Microsoft Basic Render Driver, which make the whole system ver laggy. 

Is there anything I can do to fix this?
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/3314130/a6314349-d734-4d12-9abf-3a1887f9ae36)
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/3314130/6691a654-a621-4913-8d6d-cc4d69382a68)

**Comment by link89** [comment]
And after the monitor turns dark for around 1 secs, the P106 driver lost its 3D support, and GT710 becomes normal
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/3314130/601a265f-4e55-446f-9684-ded2bb0442a7)
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/3314130/bfdec091-d342-4489-a78e-c4ca837c5294)

**Comment by dartraiden** [comment]
Use [446.14](https://github.com/dartraiden/NVIDIA-patcher/releases/tag/446.14)

In the future i will make 474.44 especially for you.

**Comment by link89** [comment]
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/3314130/87d9c488-6854-4449-adf9-0350c367af5f)
Guess still need a newer driver, it just upgrades to 456.71 automatically. Is there anything I can do to stop the auto update?

**Comment by dartraiden** [comment]
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate]
"ExcludeWUDriversInQualityUpdate"=dword:00000001
```

**Comment by link89** [comment]
The registry config doesn't work.

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/releases/tag/472.12
