### ISSUE TITLE
Graphics card installation or recognition problem.

### ISSUE THREAD

**Issue by wonheui** [dartraiden/NVIDIA-patcher#26]
Dear dartraiden,
I have a problem and I am contacting you to ask for help.
I am using Windows 11,
P106-100 or P102-100 is in use.
I played the game by installing the graphic driver version 537.13 or 536.99 uploaded by dartraiden.

(Symptom)
However, I recently ran Call of Duty during a Steam game, and the screen freezes during the game, and the game automatically shuts down.
When I checked the display adapter in Device Manager in the Windows Control Panel, the installed "NVIDIA GeForce GTX 1060 6GB" was changed to a "!" mark, and the "NVIDIA Control Panel" that was always displayed in the desktop tray was also gone.

(reinstall driver)
So I rebooted into Windows startup settings and booted selectively with "Certificate Reliability Disabled".
I deleted the graphic driver and installed the version 537.13 or 536.99 uploaded by dartraiden.
However, it shows as installed in device manager.
However, "Nvidia Control Panel" does not appear in the desktop tray,
It doesn't even show "GPU 1" in task manager.
I confirmed that the graphics card is not displayed in "GPU-Z".
![화면 캡처 2023-08-25 044021](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/694f929b-2167-40e2-bb8a-d0d28a454758)
![화면 캡처 2023-08-25 044544](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/cdb6186e-2fa3-43f3-8c59-a57ea042ed9c)

so again
Reboot normally and check Device Manager, "NVIDIA GeForce GTX 1060 6GB" is changed to "!"
![화면 캡처 2023-08-25 051438](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/4f510d8b-6cff-4dd0-8e0a-fd09f56e34fc)

So, in the normal booting state, I uninstalled "NVIDIA GeForce GTX 1060 6GB" in Device Manager and tried to install it again with "Automatic Driver Search".
The graphics card was normally found as "P106-100", but an error message appears during installation as shown in the figure below.
(You will know that it is normally installed as "P106-100".)
![화면 캡처 2023-08-25 051608](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/c73e16cc-bfb2-4325-8a1a-dda757cac16d)

(inquiry)
In this case, I would like to ask what is the problem.
If you have a hardware problem with your graphics card,
If the device manager's automatic update recognizes the graphics card normally, but an error message appears during installation...
What part of the hardware is failing?
GPU, Bios, V-Memory, etc. Which one is the problem?
ah. Of course, there is no problem with the driver uploaded by dartraiden. (I've used it before without any problems)
Dear dartraiden, I desperately need your advice.
please help me....

**Comment by dartraiden** [comment]
1. Download [DDU](https://www.wagnardsoft.com/display-driver-uninstaller-ddu-), [driver package](https://www.nvidia.com/download/driverResults.aspx/210779/) and [patched files](https://github.com/dartraiden/NVIDIA-patcher/releases).
2. Disable Internet connection
3. Use DDU to clean NVIDIA driver (without reboot)
4. Unpack driver package, replace files by patched ones.
5. Use Install.bat
