### ISSUE TITLE
FACEIT didn't work with NVIDIA driver

### ISSUE THREAD

**Issue by m6ight** [dartraiden/NVIDIA-patcher#27]
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/143213615/ddae62ee-48e5-42bd-b95c-227899866e00)
any fixes please?...

**Comment by dartraiden** [comment]
[EVRootCA.zip](https://github.com/dartraiden/NVIDIA-patcher/files/12443204/EVRootCA.zip)

Import and reboot.

**Comment by m6ight** [comment]
It doesn't help. Trouble with FACEIT AntiCheat (can install with no game)

**Comment by dartraiden** [comment]
What video card are you using?

**Comment by m6ight** [comment]
CMP 40HX

**Comment by dartraiden** [comment]
Try this
https://dropmefiles.com/qjuf3

Install manually via Device Manager as described here (Choose RTX 2070 or maybe RTX 2070 Super)

**Comment by m6ight** [comment]
wait please, after 1h i said

**Comment by dartraiden** [comment]
Btw i installed FACEIT anti-cheat as well as the client and even logged into the client. No error messages ¯\_(ツ)_/¯

**Comment by m6ight** [comment]
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/143213615/bce09775-8e05-4f70-b83b-b6d9876033e8)
may this issue?

**Comment by m6ight** [comment]
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/143213615/62757b80-ad54-44ea-a2fc-5a2361cea4f1)
not work:(

Without nvidia driver faceit anti-cheat start okay..

**Comment by dartraiden** [comment]
![263488667-bce09775-8e05-4f70-b83b-b6d9876033e8](https://github.com/dartraiden/NVIDIA-patcher/assets/5046855/0b3e7041-c4e5-41d6-ace0-5e3a1c4937b7)


where do you see this message?

**Comment by m6ight** [comment]
In install manually driver

**Comment by m6ight** [comment]
Maybe i can tell you in telegram? I can speak Russia

**Comment by dartraiden** [comment]
Same nickname as here

**Comment by dartraiden** [comment]
I re-uploaded the latest release with a fix.
