### ISSUE TITLE
CMP 170HX support

### ISSUE THREAD

**Issue by dartraiden** [dartraiden/NVIDIA-patcher#30]

**Comment by Skylord4321** [comment]
CMP 170HX?
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/61630312/4887afe0-af1d-4ef5-95e9-00319a5588b7)
they don't have opengl/vulkan/DirectX

However, I do know they are from Nvidia Tesla/Grid, you can download Tesla/Grid Drivers from them.

**Comment by dartraiden** [comment]
Technically 170 HX is supported by the driver, it's just missing the .inf entry

**Comment by Skylord4321** [comment]
interesting, how is the progress going then?

**Comment by dartraiden** [comment]
his is not difficult to implement. But I don't have such card for testing. The last few weeks have been spent learning new ways to sign drivers that don't require the use of stolen certificates.

**Comment by Skylord4321** [comment]
new ways to sign drivers without the use of stolen certificates? That's a new progress. Unfortunately, i don't have such a card as well, the only thing i have right now is the cmp 90hx. But still, that's a good progress.

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/commit/c849ccc9f839afbea67236572f2984296a426f8f
