### ISSUE TITLE
This is an inquiry regarding a recently released driver.

### ISSUE THREAD

**Issue by wonheui** [dartraiden/NVIDIA-patcher#32]
Respected dartraiden.
I have a few questions.

Windows version: Windows 11 PRO
Graphics card in use: Zotac P102-100

1. Previous releases were installed “manually (P102-100 --> 1080 TI)”.
However, recent releases are installed by “running Install.bat”.
Of course, it doesn't matter if you install the latest release "manually (P102-100 --> 1080 TI)"...
I would like to know the difference between these two methods.

2. When you install by “Run Install.bat”, it is recognized as “P102-100”, so you are installing “Manually (P102-100 --> 1080 TI)”.
I would like to know how to install it by "Run Install.bat" and change it to "1080 TI".

3. P102-100 is said to support NVENC 6th Gen.
“NVENC” appears to be a function used for video editing.
Among the two types of driver: standard and NVENC, I am curious what the different functions are for the "NVENC" version.
![화면 캡처 2023-09-09 103912](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/9dae2fc1-3c90-472d-a195-1681843a824f)

4. If you look at release 516.61...
It is marked as “the only driver that supports RTX 3080 Ti 20GB.”
Is RTX 3080 Ti 20GB also for mining?
Is RTX 3080 Ti 20GB available on the market?
I would like to know if there is a way to purchase the RTX 3080 Ti 20GB.
If you can buy an RTX 3080 Ti 20GB, you will feel like you have everything in the world.

I asked a lot of questions because I didn't know much.
Even if it's annoying, I would appreciate it if you found it cute.... ^^;;

**Comment by dartraiden** [comment]
> I would like to know the difference between these two methods.

Different sets of files and registry keys. But this is a much more correct method for CMP-cards because not all of them have an exact gaming card analog. So I switched to this method.

> I would like to know how to install it by "Run Install.bat" and change it to "1080 TI".

Edit nv_dispig.inf: Find "P102-100" and replace it with whatever you want. Then disable Secure Boot in BIOS settings (if SB is enabled) and enable test mode in Windows: `bcdedit /set testsigning on`. Reboot and run Install.bat. After installation execute  `bcdedit /set testsigning off`, reboot, and enable Secure Boot (if it was enabled originally).

> P102-100 is said to support NVENC 6th Gen.

P106-100 also has it according to https://www.techpowerup.com/gpu-specs/p106-100.c2980
But no one has yet managed to enable NVENC on this card, so this is a bug on the site.
You can try to install NVENC- prefixed driver and test NVENC (run OBS-Studio, enable NVENC in OBS-Studio options, and try to record your screen - if NVENC is not working, OBS will crash)

> I would like to know if there is a way to purchase the RTX 3080 Ti 20GB

It was sold in China. Semi-officially imported into Russia (by small companies that mainly sold mining equipment).

**Comment by wonheui** [comment]
Thank you for your clear answer...
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/ae3a7c55-b3c1-4372-a720-9f2236e3eb5b)
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/5a901a73-5a3b-4258-87ec-6c529b01765b)

1. I would like to know the difference between the two methods.
Because it's a much more accurate method for "CMP" cards...
I understand that there will be no problems at all even if the "P" series cards are installed manually.
2. I would like to know how to install with “Run Install.bat” and change to “1080TI”.
I opened "nv_dispig.inf" to edit it, but unfortunately "P102-100" was not in the list. ㅜ.ㅠ

**Comment by dartraiden** [comment]
1. Yes, you can install manually for P-cards if you want (with clearing the driver via DDU)
2. 
<img width="485" alt="notepad++_xID31SdyO1" src="https://github.com/dartraiden/NVIDIA-patcher/assets/5046855/9081bf9a-5b93-479d-9971-c69775a196b5">

**Comment by wonheui** [comment]
Uh... that's strange...
It's different from me...ㅜ.ㅜ
I opened the "nv_dispig.inf" file in the "Display.Driver" folder in the "537.13-desktop-win10-win11-64bit-international-dch-whql" folder with Notepad.
![화면 캡처 2023-09-16 154520](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/11538682-c4b1-4211-8280-59058913efb1)

As shown in the picture, “1080 TI” is followed by “P6000”.
There is no "P102-100" in between...ㅜ.ㅠ

**Comment by dartraiden** [comment]
You are editing the original file, not the one patched by me

**Comment by wonheui** [comment]
The date I downloaded version "537.13" was August 25th.
It seems that dartraiden re-uploaded it after I downloaded it on August 25th.
So I think there is a difference....
I downloaded it again and checked, and there was "P102-100".... ㅜ.ㅠ
![화면 캡처 2023-09-19 110806](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/87c79d27-b997-4b76-819d-022360632131)
![화면 캡처 2023-09-19 110916](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/ec87590b-f566-4a07-ad85-41b1a5e51830)

**Comment by dartraiden** [comment]
> So I think there is a difference....

Nope, the difference is only improved FaceIT compatibility, no changes in inf

**Comment by wonheui** [comment]
All right. I guess I made some kind of mistake...ㅜ.ㅠ
Please look cute~^^;;

**Comment by wonheui** [comment]
Respected dartraiden.
There is a difference between version 537.13 that I downloaded on August 25th and the same version that I downloaded a few days ago.
*Downloaded on August 25th*
You can select “HD Audio Driver” as shown in the picture.
![2023 08 25](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/ca3edafe-6237-4fd0-a401-b2acceb595f5)

*downloaded a few days ago*
There is no "HD Audio Driver" as shown.
![화면 캡처 2023-09-21 165949](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/1ce4eecc-0b43-49e3-9b7e-b046cc70b378)

There is one thing I would like to ask you.
It would be nice to be able to apply the “HD Audio Driver” optionally in future releases.
I request this with a respectful heart.
I always use it with a grateful heart.
