### ISSUE TITLE
Incompatibility with some dx12 games on 537.13

### ISSUE THREAD

**Issue by hiedaze** [dartraiden/NVIDIA-patcher#33]
Specs: i5-4570_P106-090
i7-8850H(ES)_P104-100
Problem: When i opened some dx12 games like valorant, RoTR, they try to use the intergrated one (GPU-0) and the whole system lags or crashed with black screen (music still on)

**Comment by dartraiden** [comment]
1) Make sure that the discrete graphics card (mining) has support for 3D acceleration (see GPU-Z output)
2) In Windows 10 open the NVIDIA control panel and set the mining card as a primary graphic adapter.
2) In Windows 11 open `Settings` → `System` → `Display` → `Graphics` → `Change default graphic settings` and set mining card as default high-performance graphic adapter.

**Comment by hiedaze** [comment]
Only those games i tried has this problem, older driver and other apps (even chrome) is using GPU-1 (3d accel driver). 
I have been using your patch for a long time, and this driver version is the first one that got this issue.

**Comment by hiedaze** [comment]
@dartraiden i tried to follow your guide but don’t find any settings like them in both windows 10 and windows 11, is there any reg keys i need to add alongside?

**Comment by dartraiden** [comment]
All necessary registry keys are added when installing the driver. Is your Windows 10 is LTSC?

**Comment by hiedaze** [comment]
> All necessary registry keys are added when installing the driver. Is your Windows 10 LTSC or regular Windows 10?

It’s genuine windows 10 pro. I have never used LTSC

**Comment by dartraiden** [comment]
Open regedit: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}`

There you will see subkeys `0000` and `0001`. One of them is integrated graphics, the second is Nvidia

NVIDIA subkey should contain `AdapterType = 1` and `EnableMsHybrid = 1` keys

<img width="706" alt="regedit_NA5qSyLHbe" src="https://github.com/dartraiden/NVIDIA-patcher/assets/5046855/4e9612f3-886b-4619-b64e-d3cdfe3cd3e6">

**Comment by mike5551963** [comment]
приходиться для каждой задачи указывать конкретную карточку , глобальные установки отсутствуют, ключи реестра на данную ситуацию не влияют, операционнки 10 и 11 последние
