### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by xpower1** [dartraiden/NVIDIA-patcher#35]
nvidia seems to have fixed the error I couldn't use any driver from 3 hours ago

**Comment by operador777** [comment]
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/19232315/3976f0e7-2212-4f2c-b691-2d38727348ff)

It works correctly for me, make sure to follow the instructions and when checking the driver, ensure it is signed by "Edgard Roberto Viera."

Furthermore, make sure you do not have the KB5028166 update for Windows 10 installed, as this July update blocks the use of digitally signed drivers from uncertified sources.

**Comment by dartraiden** [comment]
> ensure it is signed by "Edgard Roberto Viera."

It is an old revision, incompatible with FaceIT anti-cheat. Latest release signed with "Atheros"
