### ISSUE TITLE
The driver cannot launch a particular game but other games work normally from same company

### ISSUE THREAD

**Issue by intertiexd** [dartraiden/NVIDIA-patcher#37]
I tried playing two different games from mihoyo: Genshin Impact and Honkai: Star Rail.
Genshin Impact launched successfully but HSR will stuck at the mihoyo/hoyoverse logo screen. It would not get pass that screen and the program will become not responsive.
Maybe there is a fix or I did something wrong? Thanks in advance.

**Comment by operador777** [comment]
I could assist you in identifying the issue with the game if you could share the .log file with me for analysis and to determine whether it is related to the graphics card or its driver. Please conduct some research on the file path for the .log of that specific game and, if feasible, attach it.

**Comment by intertiexd** [comment]
The problem is solved with your latest 545.84 driver patch. No more crashes anymore!
