### ISSUE TITLE
проблема установки p106-100

### ISSUE THREAD

**Issue by mike5551963** [dartraiden/NVIDIA-patcher#38]
карточка p106-100 c помощью Вашего последнего драйвера 537.17 и патча для него установлена правильно  система win11 ( пробовал и на win10) видит без ошибок, gpu-z  определяет карточку правильно, за вывод на монитор отвечает hd7770. установлена правильно, проблема p106-100 не встает высокопроизводительным адаптером, поэтому работает только hd7770.прошу помочь в решении проблемы, заранее благодарю
![IMG_20230926_140110](https://github.com/dartraiden/NVIDIA-patcher/assets/146029970/2477e106-c1ca-4970-91c6-04f4cc16ac9b)
![IMG_20230926_140156](https://github.com/dartraiden/NVIDIA-patcher/assets/146029970/26018d2b-9eb4-485d-866f-90bff385bbdf)
![IMG_20230926_140206](https://github.com/dartraiden/NVIDIA-patcher/assets/146029970/387d50a9-67c8-4fbe-9f8c-e867f851d7b1)
![IMG_20230926_140415](https://github.com/dartraiden/NVIDIA-patcher/assets/146029970/b54e568f-e61b-407d-80fe-27ab216970ed)

**Comment by mike5551963** [comment]
описка драйвер и патч 537.13

**Comment by dartraiden** [comment]
На Windows 11 в панели управления NVIDIA переключателя и не будет, т.к. в этой ОС выбор видеокарты уже есть нативно.

См. пункт 8.2. в ридми.

**Comment by mike5551963** [comment]
значит для данных карточек ,необходимо каждой задаче указывать -работать с высокопроизводительной картой( у меня сейчас так функционирует), а старый метод глобального указания , не работет ?

**Comment by dartraiden** [comment]
<img width="960" alt="ApplicationFrameHost_7ieVl0XzmR" src="https://github.com/dartraiden/NVIDIA-patcher/assets/5046855/1aa29829-9460-46c5-9a15-8de09848211a">
