### ISSUE TITLE
 P106-100 not detected by system after crash (BSoD) using Nvidia 531.41 driver update

### ISSUE THREAD

**Issue by dubezOniner** [dartraiden/NVIDIA-patcher#4]
I patched the Nvidia 531.41 driver and updated from 417.22 successfully (selecting GTX 1060 6GB) , then I tried to run Superposition benchmark on my P106-100 and got a Blue Screen error. Now afterwards the card is no longer being detected by the system. 

I had noticed in GPU-Z that Ray-Tracing was enabled after the update even though these are non-RTX cards, could it be possible that the benchmark tried to do RTX resulting in a hardware failure? Has anyone else experienced this issue?

**Comment by dartraiden** [comment]
Raytracing can work on non-RTX cards (with terrible performance), so it's doubtful that this can cause the adapter to fail.

**Comment by dubezOniner** [comment]
Is it possible to get this patch to work with the newer mining cards i.e. NVIDIA CMP 30HX, 40HX, etc?

**Comment by dartraiden** [comment]
for CMP-cards it is better to use this driver https://linustechtips.com/topic/1029382-hacking-nvidias-drivers/?do=findComment&comment=15867219

But I don't see the point, because these cards have a x4 bus. Terrible gaming performance.

**Comment by dartraiden** [comment]
CMP-cards compatibility fixed in latest release.

In addition, at least on the CMP 40HX, the bus can be increased from x4 to x16 by soldering the missing components near the PCI-E slot.
