### ISSUE TITLE
Is it possible to use nvidia shadowplay on cmp40hx?

### ISSUE THREAD

**Issue by ssasa1** [dartraiden/NVIDIA-patcher#40]

**Comment by dartraiden** [comment]
IF this card supports nvenc and nvidia software does not contain a lock prohibiting shadowplay on such cards = yes.

**Comment by operador777** [comment]
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/19232315/13938603-686e-4379-a037-dc8bcc038b78)

I have the same graphics card. To enable Nvidia ShadowPlay, you need to follow these steps:

Important: Make sure you have GeForce Experience installed.

1: Go to the installation path of Nvidia GeForce Experience, which is usually: C:\Program Files\NVIDIA Corporation\NVIDIA GeForce Experience.
2: Once there, locate the executable named "NVIDIA Share.exe" and create a desktop shortcut for it.
3: After creating the shortcut on the desktop, double-click it, go to its properties, and in the "Target" field at the end of the path, add "  --shadowplay" without the quotes, as shown in the picture. Click apply and then accept.
4: Now, double-click the shortcut again, and it may seem like nothing happens. However, when you press alt + z, the Nvidia ShadowPlay overlay will open.

I hope this helps.

**Comment by ssasa1** [comment]
I did everything according to the instructions but it didn't work.Thank you for trying to help my problem

**Comment by operador777** [comment]
Oh, it's strange, it works perfectly for me as you can see. Can you show me how you edited your shortcut?
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/19232315/4d31ff2c-3602-45f1-85fe-c7aac3700e98)

![image](https://github.com/dartraiden/NVIDIA-patcher/assets/19232315/a5cc7620-ad30-4659-a8f9-494d678187d2)

**Comment by ssasa1** [comment]
![2023-10-05_17-42-03](https://github.com/dartraiden/NVIDIA-patcher/assets/146658457/17a64b7f-4960-4678-9562-a70f057a615f)

**Comment by operador777** [comment]
Make sure to:
- Have the latest version of GeForce Experience.
- Run GeForce Experience and log in to the application (if you don't have an account, create one).
- Have the CMP 40 HX as the primary graphics adapter.
- Run the shortcut created earlier as an administrator.

**Comment by operador777** [comment]
It seems like you're right. I just performed a clean installation of all the drivers, using the latest NVENC version, and after completing the entire process, it appears that ShadowPlay is not working.

Previously, it was working with the version "Updated 24.08.2023: Fixed broken 3D acceleration for CMP XX cards."

However, with the new one that includes NVENC support, it's not functioning.

**Comment by dartraiden** [comment]
Weird... I just replaced signature, nothing else was changed...

**Comment by dartraiden** [comment]
If you still have the driver that NVENC worked with, please upload it somewhere

**Comment by operador777** [comment]
Update: Shadowplay is working in the latest version (537.58), update and follow the steps I provided earlier.

**Comment by dartraiden** [comment]
> Shadowplay is working in the latest version

With regular or NVENC-prefixed driver?

**Comment by operador777** [comment]
> > Shadowplay is working in the latest version
> 
> With regular or NVENC-prefixed driver?

For me it works perfectly in both versions; I just tested it.

**Comment by dartraiden** [comment]
Closed as answered.

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher#using-shadowplay-also-known-as-the-nvidia-overlay

**Comment by DesperatoACE** [comment]
> If this card supports NVENC and Geforce Experience does not prohibit Shadowplay on such cards = yes.

Is it possible to cheat the game with the video card model? I wanted to play Minecraft rtx, but I can't enable ray tracing because it's blocked. It says your video card does not support ray tracing. :(

**Comment by dartraiden** [comment]
It is unlikely that the game determines the raytracing support by GPU name.
