### ISSUE TITLE
Есть ли способ получить пропатченный драйвер старой версии?

### ISSUE THREAD

**Issue by RaySinner** [dartraiden/NVIDIA-patcher#41]
Я хотел бы получить пропатченый драйвер старой версии 341.хх - 391.35 может завалялся у кого ? ))

**Comment by dartraiden** [comment]
До 417.22 включительно достаточно установить драйвер и поменять два ключа в реестре:
https://youtu.be/dkE4aAVUIzU

**Comment by RaySinner** [comment]
> До 417.22 включительно достаточно установить драйвер и поменять два ключа в реестре: https://youtu.be/dkE4aAVUIzU

Дело в том что мне друг майнер подарил видавшую виды p104 и сказал что есть гениальный чел который придумал как юзать их в играх , я так понимаю что это ты :) , у меня комп зион без видео ядра и затычка gtx560. Если я накатываю твой драйвер p104 определяется системой как ты и говоришь в своих гайдах, но отваливается gtx560 так как ее поддержка уже отсутствует в современных драйверах. А если накатываю драйверы gtx560 тогда отваливается пропатченный драйвер. Вот я и подумал что если найти пропатченный драйвер в котором есть поддержка gtx560 и gtx1070 то это может сработать. На моей p104 так же есть порт DisplayPort но мне кажется он использовался на производстве как системный разъем и биос какрты его не поддерживает. Подскажи пожалуйста как можно поступить в моей ситуации, а то я прямо хочу завести эту карту, но пока не знаю как )) может купить затычку AMD или это тоже не сработает?
