### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by operador777** [dartraiden/NVIDIA-patcher#43]
Hello, how are you? First of all, I want to thank you for everything you do; you help us a lot, especially those of us who have mining GPUs and want to use them for gaming.
On another note, will there be a new version of the driver? The latest version is 537.42.

https://www.nvidia.es/download/driverResults.aspx/211805/es

**Comment by dartraiden** [comment]
Will be done when it's done. Now I'm busy preparing for the release of [my other project.](https://github.com/miranda-ng/miranda-ng)

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/releases/tag/537.58
