### ISSUE TITLE
Вопрос по поводу работы на 2-3 поколении интела

### ISSUE THREAD

**Issue by arseniy0924** [dartraiden/NVIDIA-patcher#46]
Остались ли проблемы с установкой драйверов, когда нужна определенная версия windows? Будет ли работать на серверной supermicro под два 1366? Проца, там есть встроенная в материнку видеокарта.

**Comment by dartraiden** [comment]
Нужна Windows 10 или новее.

На ранних поколениях обычно видеокарта висит с сообщением о нехватке ресурсов.

**Comment by arseniy0924** [comment]
Попробовал с i5 2300 на чистой винде, драйвера установились, но нагружать именно дискретку не захотело(
