### ISSUE TITLE
New NVENC version 537.58 is not working on CMP 40HX.

### ISSUE THREAD

**Issue by operador777** [dartraiden/NVIDIA-patcher#47]
The new NVENC version seems to not be working on the CMP 40HX (which has NVENC support), The regular version is working properly. I am following the steps correctly as in previous versions, which did work, but this one is not installing properly. What could be happening?

![image](https://github.com/dartraiden/NVIDIA-patcher/assets/19232315/57c3f771-c4e5-4e57-a07c-fbdbae46c3cf)

**Comment by dartraiden** [comment]
Yes, it was uploaded by mistake and now removed.
Currently there is no patch for this version.
https://github.com/keylase/nvidia-patch/blob/master/win/README.md

**Comment by dartraiden** [comment]
Uploaded driver with NVNEC support.

**Comment by phicha20224** [comment]
does p104 or CMP 70Hx support NVNEC  ?
please help recommend me what card is good. Thank You

**Comment by dartraiden** [comment]
Seems like P-cards does not support NVENC. CMP more likely.
