### ISSUE TITLE
RTX 3080 Ti 20 GB

### ISSUE THREAD

**Issue by alexvorodis** [dartraiden/NVIDIA-patcher#48]
Будет ли обновляться драйвер для этой карты?
Текущий (516.61) отлично работает со старыми играми, но вот с ультрасовременными или ругается или крашится.
Например, такое происходит с киберпанком или дьябло 4.

**Comment by dartraiden** [comment]
Не будет, пока я не найду оригинальный 516.61, чтобы сравнить и узнать, что там сделали китайцы.
