### ISSUE TITLE
RTX 3080 Ti 20 GB

### ISSUE THREAD

**Issue by alexvorodis** [dartraiden/NVIDIA-patcher#49]
Этот подойдёт?

https://support.lenovo.com/ru/ru/downloads/DS555060

Если не скачать, я на свой яндекс.диск ссылки даю:

https://disk.yandex.ru/d/Rm8-cKDLOwmlsQ

https://disk.yandex.ru/d/VtFo74Qfyzft-w

**Comment by dartraiden** [comment]
Нет, этот я видел. Он кастрирован и заточен под Леново.

**Comment by alexvorodis** [comment]
Переполошил всех, кого только можно. Ближайшая версия, которая есть в сети:
https://www.techpowerup.com/296266/nvidia-geforce-516-59-game-ready-drivers-released
Не подойдёт?

**Comment by dartraiden** [comment]
В том и соль, что нужен в точности тот же билд. Как уже говорилось, даже одинаковые версии, но разные билды имеют массу отличий.

**Comment by CITDL** [comment]
Приветсвую!
Можно ли как то самому делать, возможно через какую то программу обновление драйвера для данной карты?
Использую данную карту для игр и не хотелось бы в моменте оказаться неработоспособным.
Ваш драйвер установил, работает отлично, спасибо за создание.

**Comment by dartraiden** [comment]
Нет, потому что я так и не знаю, что надо менять в драйвере, чтобы карта заработала.

**Comment by eXzExZ** [comment]
OK, cool, verified it works. Will information for the video card be added to the main release?

**Comment by dartraiden** [comment]
[Done](https://github.com/dartraiden/NVIDIA-patcher/releases/tag/556.12)
