### ISSUE TITLE
CMP-70HX не хочет работать как надо

### ISSUE THREAD

**Issue by servicePNH** [dartraiden/NVIDIA-patcher#53]
Карта Palit CMP 70HX 8GB GDDR6X 256bit X   NED70HX014P2-1046A ( device id 10DE 248A - 10DE 248A )
Winidows любой, 10 или 11 без разницы, официальная версия с последними обновлениями, на всём попробовал.
Драйвера тоже пытался ставить все, что доступны на странице скачивания.
Платформы разные, от i3 4130 до i7 11800 es
Вывод на монитор через встройку, через дискретную GTX1060
Ранее запускал P104-100 на всех этих платформах, работало без проблем с первого раза.

Всё делаю по инструкции, то есть сношу драйвера в безопасном режиме, запрещаю установку из центра обновлений, вижу устройство в диспетчере, ставлю патченый драйвер, GPU-Z отображает все галочки. 
Диспетчер задач находит устройство с восклицательным знаком NVIDIA Platform Controllers and Framework. код ошибки 31, если перевести систему в тестовый режим иногда код 52.

Со встройкой intel всё вроде как видится, можно выбрать как в программе настроек NVIDIA, так и в настройках Windows предпочтительный адаптер для 3D, но всё равно все программы тестовые (3D Mark, Superposition и другие) и игры (Киберпанк, ФарКрай 5 и 6, и другие ) не видят видеоускорителя а работают исключительно на встройке.
С дополнительной 1060, соотвтетственно, всё работает на 1060, но выбор предпочтительного адаптера уже не показывает наличия CMP-70HX в системе.

Менял версии драйверов, ставил Windows "с нуля", руками менял через диспетчер устройств карту на RTX3070, на RTX3070ti - толку нет, ничего не помогает.

Ещё в системном трее висит какой-то квадратный значок, если по нему кликнуть, появляется окошко с вкладками про все карты nvidia, которые есть в системе, и по поводу CMP 70HX написано "этот графический адаптер сейчас не используется", " к этому графическому процессору не подключены мониторы"

Карта сама по себе исправная, пробовал на нескольких картах - все ведут себя одинаково. В майнинге карта работает без проблем.

**Comment by servicePNH** [comment]
Пока жду ответа, провёл ещё ряд издевательств над картой:

- во-первых, замерил ток потребления по доппитанию +12В амперметром, получилось в районе 5 Ампер, то есть жрёт карта 60 Ватт как в простое, так и в нагрузке, ни капельки ничего не меняется и про что там GPU-Z и остальные программы рисуют про загрузку 100% - вопрос интересный.

- впаял БИОС от 3070Ti ( https://www.techpowerup.com/vgabios/234439/palit-rtx3070ti-8192-210428-1 ), наиболее походящий отличается на одну цифирь в ID, ожидаемо не помогло, карта запустилась, но видит 0 памяти, по шине ничего не изменилось, Несмотря на бодрое заявление GPU-Z, что карта может 4.0, так и остался 1.1, карта на этот момент торчала в 3.0, другие карты видятся там именно как 3.0, родной БИОС вернул на место. Кстати, именно в этой карте конденсаторы не 220 нФ, как в CMP40HX в ролике на ютубе, а 150 нФ, по крайней мере родные именно такие стоят на 4-х линиях, типоразмер аналогичный 0402. Кто уже успел купить/заказать на 220нФ - не переживайте, тоже заработает, там не принципиально, по другим картам от 100 до 330 попадаются конденсаторы в этих линиях, работает всё, единственное что, для удовлетворения собственного префекционизма можно будет тогда и те 8, что уже запаяны, поменять на 220.

- добился установкой патченых драйверов 472.12 отсутствия устройств с восклицательными знаками, но это ничего в общей картине не поменяло.

Складывается впечатление, что не хватает какого-то ключика в реестре или в каком ini файле, где устанавливается именно эта карта как ускоритель. То есть, всё происходит по аналогии с P104-100, но вот где-то какой-то номер карты или ещё там что-то не на ту карту ориентируется, а на встройку.  Тот софт, который напрямую к карте обращается, например, программы для майнинга, всё равно ( имеется в виду при установке патченых драйверов и при ручном переименовании карты в 3070 ) видят карту как CMP 70HX и работают с чипом в полной мере, там и ток потребления меняется в зависимости от нагрузки, и производительность карты на уровне 3070ti, то есть, всё, как положено.

**Comment by dartraiden** [comment]
Если меняли вручную на 3070/3070 Ti, то дело явно не в inf.

**Comment by servicePNH** [comment]
У меня вот нету оригинальной 3070, чтобы проверить, как с ней работает. Сделать из этой 3070 не получилось, она висит с жёлтым восклицательным знаком и GPU-Z её видит снулевой памятью. Но факт, что она даже не пытается грузиться, хотя тот же GPU-Z настаивает, что карта на 100% загружена по ГПУ.

Я так понимаю, у вас нет такой карты на проведение своих исследований? По другим сообщениям получается, что такие проблемы на картах 50, 70 и 90 вылезли у всех. В принципе, если надо карту - может как-то скооперируемся, потому как без ваших патчей карты всё равно повисли мёртвым грузом,

**Comment by dartraiden** [comment]
Нет ни карты, а в результате недавнего трагического происшествия, теперь ещё и времени :(

**Comment by servicePNH** [comment]
Жаль... Тогда не буду вас доставать вопросами. Но дело вы затеяли очень полезное, будем надеяться, что кто-то подхватит идею.

**Comment by dartraiden** [comment]
Закрою, как дубликат https://github.com/dartraiden/NVIDIA-patcher/issues/54
