### ISSUE TITLE
Можно, пожалуйста, предыдущую версию драйвера

### ISSUE THREAD

**Issue by astronautduckpc** [dartraiden/NVIDIA-patcher#58]
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/144943269/b74da799-7f8e-46ca-849a-196048a295ce)

Можно тот, что был тут до этого? он мне нравился лучше, использую на core i  - 3го поколения. Спасибо

**Comment by ArkQuark** [comment]
https://github.com/dartraiden/NVIDIA-patcher/releases
вот все версии драйвера которые есть, я использую 537.58
![изображение](https://github.com/dartraiden/NVIDIA-patcher/assets/74979909/856e0b41-2e79-4558-b784-720b7f9dc259)

**Comment by dartraiden** [comment]
Я теперь оставляю две последние версии, так что да, скачайте 537.35 из релизов, она и есть предпоследняя.

**Comment by dartraiden** [comment]
Наверное, стоит завести какой-то архив предыдущих версий
https://github.com/dartraiden/NVIDIA-patcher/issues/59

**Comment by astronautduckpc** [comment]
> Наверное, стоит завести какой-то архив предыдущих версий #59
Я прошу прощения, это я сам виноват, дело было в дровах встройки. 
Но архив да, не помешал бы.. Я бы так быстрее понял бы свою ошибку)
Еще раз прошу прощения
