### ISSUE TITLE
Command Line Error: Cannot find archive when trying to patch driver version 535.98

### ISSUE THREAD

**Issue by alwanyassin** [dartraiden/NVIDIA-patcher#6]
I'm trying to patch the latest driver but there is an error message in the patch.bat progress but the progress is still going until it finished (Patch.bat windows closed automatically). Never seen that with older driver before. Is that a problem?

![Screenshot 2023-05-31 063054](https://github.com/dartraiden/NVIDIA-patcher/assets/43112324/51d80167-e504-4e63-afb1-5461d4f4c7e3)

**Comment by dartraiden** [comment]
Looks like Nvidia has stopped packaging binaries with makecab utility. No more bi_, dl_, ex_, ic_, and sy_ files.

7z e "%DRIVER%\*.bi_" -o"%DRIVER%"
7z e "%DRIVER%\*.dl_" -o"%DRIVER%"
7z e "%DRIVER%\*.ex_" -o"%DRIVER%"
7z e "%DRIVER%\*.ic_" -o"%DRIVER%"
7z e "%DRIVER%\*.sy_" -o"%DRIVER%"
