### ISSUE TITLE
Request to share the latest version.

### ISSUE THREAD

**Issue by wonheui** [dartraiden/NVIDIA-patcher#61]
Respected Dartreiden... Hello...
I am a P102-100 user.
I'd like to try "Alan Wake 2", one of the newest games...
You cannot play the game "Alan Wake 2" because the version currently being shared is 537.58. ㅜ.ㅜ (The game is not smooth)
Confirmed that minimum version "545.92" is supported.
Additionally, the soon-to-be-released "Call of Duty: Modern Warfare III" is expected to be supported starting from version "546.01".
So, I dare to ask you a favor.
We would appreciate it if you could share a version "545.92" or higher.
If possible, it would be better if you could share the latest version, "546.01". ^^
I sincerely ask you to do so.
Then have a healthy and happy day~~

![스크린샷 2023-11-02 023424](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/8a54b787-058d-424a-a567-1d6548ebf7b8)

![스크린샷 2023-11-02 024458](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/87d1ef3c-3731-4c7b-96eb-5d5ed7f35e3c)

**Comment by dartraiden** [comment]
Done.

**Comment by wonheui** [comment]
Thank you so much.
I respect you.~~^^
