### ISSUE TITLE
P106-100 Working with Proxmox

### ISSUE THREAD

**Issue by Paffo** [dartraiden/NVIDIA-patcher#65]
Hello,
Before trying this driver i was using the card with my Proxmox server, spoofing the VID&PID to make it detect as a GTX 1060.
This was working and the official driver with no modification was getting installed
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/15388318/31c2dd11-d8aa-4bca-bc49-b5405712d59e)
but the performaces were around halved.

Removing the spoofing and installing this driver, i managed to get full performances instead.
I was just curious if you could tell me why this was happening?

Currently running your driver in a proxmox W10 VM + Fake display driver lets me use this as a Game Streaming service always accessible from anywhere, i'm loving it and it's all thanks to you

**Comment by bryanc12** [comment]
Maybe the bus interface?

**Comment by Bendy3192** [comment]
@Paffo I know, I’m too late, but how you get work fake display with P106-100. I spent too much hours, but I still can use VDD normally without at least 1 video output, which p106-100 missing. I’ve already accept NVENC missing on my gpu, OK, I can’t use cpu software decoding, but how to use Virtual Display without VNC/SPICE? Parsec virtual driver also showing black screen..

**Comment by Paffo** [comment]
> [@Paffo](https://github.com/Paffo) I know, I’m too late, but how you get work fake display with P106-100. I spent too much hours, but I still can use VDD normally without at least 1 video output, which p106-100 missing. I’ve already accept NVENC missing on my gpu, OK, I can’t use cpu software decoding, but how to use Virtual Display without VNC/SPICE? Parsec virtual driver also showing black screen..

VDD is pretty good, but if you want the "no clicks" experience of having the software do it all for you, use Apollo instead of Sunshine, it sets up everything automatically.
for the driver, use the Dartainer one (as the chinese Raincandy is not updated anymore) and enable "fake gpu".

**Comment by Bendy3192** [comment]
@Paffo Huge thanks for the reply! I understood everything, but what is fake Gpu? Do you mean Vendor ID:      0x10DE
Device ID:      0x1C03
