### ISSUE TITLE
I would like to request patch version 546.29.

### ISSUE THREAD

**Issue by wonheui** [dartraiden/NVIDIA-patcher#72]
Respected dartraiden.
We would like to request that the Nvidia driver has been updated to version 546.29.
I would appreciate it if you could patch and upload version 546.29.
[Call of Duty: Modern Warfare 2] Updated application profile [4372908]
I earnestly request this.

![화면 캡처 2023-12-05 164011](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/6841d354-c7f1-48c7-be83-321b6375f174)

**Comment by huyhung411991** [comment]
Hotfix 546.31 was also released.

**Comment by wonheui** [comment]
> 핫픽스 546.31도 출시되었습니다.

Ah yes...
I couldn't install the hotfix.
So I only patch the official version..^^

**Comment by wonheui** [comment]
Respected dartraiden...
If you play the Call of Duty: Modern Warfare 2 2022 Campaign...
During certain sections of the game, FPS tends to stay below 20.
So we desperately need the patched version 546.29.
please.~~~~

**Comment by dartraiden** [comment]
Done.

**Comment by wonheui** [comment]
Respected dartraiden...
Thanks for uploading.
I respect you.~~^^
