### ISSUE TITLE
I would like to inquire about the most recently released version 546.17.

### ISSUE THREAD

**Issue by wonheui** [dartraiden/NVIDIA-patcher#74]
Respected dartraiden.
I have one question, so I would like to inquire.
This is about the latest released version 546.17.
Graphics card model: P102-100
Games:  Call of Duty Modern Warfare 3 2023 Warzone, Call of Duty Modern Warfare 2 2022 Campaign...
If you look at the graphics settings...
In the “Upscaling / Sharpening” section...
Because the graphics card I use is P102-100...
You need to select “Nvidia Image Scaling” for upscaling...
If you select "Nvidia Image Scaling"...
The "Rendering Resolution" section is locked.
However, if you select “FIDELITYFX CAS” for upscaling...
“Rendering Resolution” is now unlocked properly.
P102-100 is an Nvidia GPU, and although the graphics driver is also an Nvidia driver...
I am asking because it is strange that "Rendering Resolution" works normally when selecting AMD's "FIDELITYFX CAS" instead of "Nvidia Image Scaling".

Note that...
In previous released versions, “Rendering Resolution” worked normally when “Nvidia Image Scaling” was selected.

![20231208121059_1](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/f5eacdf1-f13b-4e22-83ad-f4ba2536fc2d)
![20231208121042_1](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/461eda31-7027-4c85-aed1-0dc0ffa8241f)
![20231208184543_1](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/1a50ea23-cab5-4296-be0a-f3a3d2a89269)

**Comment by dartraiden** [comment]
AMD is more loyal, for example, FSR works on any cards, and DLSS only on RTX.

Probably, the game recognizes by the device ID of the video card that this is not a gaming video card, so it disables image sharpening.
