### ISSUE TITLE
I would like to request release 546.33.

### ISSUE THREAD

**Issue by wonheui** [dartraiden/NVIDIA-patcher#76]
Respected dartraiden...
As soon as I turned around, a new version, 546.33, came out.
We request you to upload patched 546.33.
I always download it with a grateful heart.~~^^

![화면 캡처 2023-12-13 152645](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/92916aed-2cf5-4821-9017-903eb127a5ba)

**Comment by dartraiden** [comment]
+

**Comment by wonheui** [comment]
Respected dartraiden...
I will always remember to be grateful to our respected dartraiden.~~
영상 영상
