### ISSUE TITLE
Driver version 372.70

### ISSUE THREAD

**Issue by Vtfelker** [dartraiden/NVIDIA-patcher#79]
For external GPU adapters we need driver version 372.70. Could you upload that version?

**Comment by dartraiden** [comment]
If the driver version is less or equal 417.22

`nvidia-smi`

![1 T3oo13vs9JdVWyR2qRvAYw](https://github.com/dartraiden/NVIDIA-patcher/assets/5046855/5a440338-d69a-443c-8c23-ea7d32699051)

Note the number of the graphics adapter (`0` if only one NVIDIA adapter present in the system)

`nvidia-smi -g 0 -dm 0`

where -g 0 is GPU number
