### ISSUE TITLE
Driver 418

### ISSUE THREAD

**Issue by Tim-ga** [dartraiden/NVIDIA-patcher#82]
Здравствуйте. Есть ли возможность пропатчить 418 драйвер?

**Comment by dartraiden** [comment]
Конкретную ссылку дайте на него.

**Comment by Tim-ga** [comment]
https://www.nvidia.com/Download/driverResults.aspx/142280/ru/

**Comment by dartraiden** [comment]
https://disk.yandex.ru/d/L0JA_mIekfhnlQ

**Comment by Tim-ga** [comment]
Огромное вам спасибо!
