### ISSUE TITLE
How to upgrade 472.12 to 472.13 and next 472.14

### ISSUE THREAD

**Issue by GermanAizek** [dartraiden/NVIDIA-patcher#84]
@dartraiden,
I would like to pick up new security patches and add 3D acceleration for CMP. Do you have saved ida pro project, or rizindb, what do you use? Why are there no source patches for 3d acceleration CMP gpu? At least name offset function or write it a pattern in Readme.md

**Comment by dartraiden** [comment]
I'm using a custom PowerShell script written by a friend specifically for my needs. He's still debugging it, but plans to publish it in the future. The script accepts a regular text file with commands.It modifies .inf-files, patches .dll and .sys using the search-and-replace method, and then signs everything with digital signatures. Search-and-replace patterns are available in the old repository (this is my self-written batch file that I used before)

https://github.com/dartraiden/NVIDIA-patcher/blob/old_patcher/Patch.bat#L20C1-L21C93

**Comment by dartraiden** [comment]
The main problem is that if you patch the driver, you need to sign it. Either with your self-generated certificate (with test mode enabled in Windows), or with some leaked certificate (I use the Atheros certificate)

**Comment by GermanAizek** [comment]
Many thanks for more information patching, as I patch newer updates, I can merge them to you.
