### ISSUE TITLE
Nvidia ReBAR on CMP cards

### ISSUE THREAD

**Issue by GermanAizek** [dartraiden/NVIDIA-patcher#85]
@dartraiden,
Is there information on your patched drivers is this feature available for all CMP cards?

**Comment by Sal-gamer** [comment]
ReBAR only works on pcie 3.0 but cmp uses pci 1.0 at 16x maximum

**Comment by Sal-gamer** [comment]
If possible, I also want to use it, but it doesn't meet the requirement.

**Comment by dartraiden** [comment]
` it has been an optional feature since PCI-E 2.0`
https://www.patreon.com/posts/look-at-modern-e-44371506

Since we only have 1.1, the answer is probably "no".
