### ISSUE TITLE
p104-100 и p106-90

### ISSUE THREAD

**Issue by astronautduckpc** [dartraiden/NVIDIA-patcher#87]
Hello. Question about unlocking pci express lines for p104-100 and p106-90. No information. The only thing I found that was clearly related to your part. Tell me, is this even possible or not?
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/144943269/9ee7bdc4-8413-42f9-a392-b3962f682ac8)

https://tiebac.baidu.com/p/8110187478?lp=home_main_thread_pb&mo_device=1

**Comment by dartraiden** [comment]
The first message is copy-paste from https://boosty.to/illario/posts/493427b8-71e0-4127-a4ad-2ebe458adf2c

The second message describes how I modify the driver

**Comment by dartraiden** [comment]
Разведены, но обрезаны ли они на аппаратном уровне в чипе или обрезаны программно в биосе, вот вопрос.

**Comment by Achtungboi** [comment]
В том-то и дело, что распаяны четыре линии и используются четыре линии

**Comment by astronautduckpc** [comment]
> Разведены все, но используется всё равно 4? Если да, то либо они обрезаны на физическом уровне на уровне чипа, либо в биосе. С первым мы бессильны, а второе пока никто не смог ещё расковырять.

дайте фотки
