### ISSUE TITLE
можно ли подружить 550ti и cmp40hx?

### ISSUE THREAD

**Issue by ssasa1** [dartraiden/NVIDIA-patcher#88]

**Comment by dartraiden** [comment]
Насколько я вижу, последний доступный драйвер для 550Ti - 391.35, а он не поддерживает CMP 40HX

**Comment by ssasa1** [comment]
А такой драйвер можно изготовить?

**Comment by dartraiden** [comment]
Это может сделать только NVIDIA.

чт, 8 февр. 2024 г., 18:46 ssasa1 ***@***.***>:
