### ISSUE TITLE
Error when installing patch driver after Windows update "2023-07 Cumulative Update for Windows 11 for x64-based Systems (KB5028182)".

### ISSUE THREAD

**Issue by wonheui** [dartraiden/NVIDIA-patcher#9]
Error when installing patch driver after Windows update "2023-07 Cumulative Update for Windows 11 for x64-based Systems (KB5028182)".
hello.
Thank you for always uploading good patch files.
I am a Windows 11 user.

However, after the Windows update "2023-07 Cumulative Update for Windows 11 for x64-based Systems (KB5028182)" the nvidia driver became disabled.
Device Manager -> Display Adapters -> I can see that "NVIDIA GeForce GTX 1060 6GB" is disabled.
NVIDIA GeForce GTX 1060 6GB When checking resources in properties it says "The resource is unavailable due to a device problem."
![windows update](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/ecdf8136-ef5a-40da-804c-f635126db0b2)
![device manager screenshot](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/51c0d3d0-e7bf-4aba-9b5f-2fce4ed0f36c)
![NVIDIA GeForce GTX 1060 6GB Properties](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/b9bd8b17-8606-4de8-95d1-1093d472118e)

So I deleted the graphics driver and reinstalled it, but the error occurred with the same result.
![Error when reinstalling patched driver](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/5ee00d37-05d2-4cce-8504-d66cea512ce4)

So, inevitably, I removed "Security Update for Microsoft Windows (KB5028182)" from Settings -> Windows Update -> Update History -> Uninstall Updates.
![uninstall update](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/e165743b-de3e-4396-8da2-843f4ab58f0c)

Then after booting "NVIDIA GeForce GTX 1060 6GB" was activated normally.
![NVIDIA GeForce GTX 1060 6GB is enabled normally](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/33a4f703-7e5a-4177-b88d-be86afe3cfa4)

It seems that you shouldn't install "Security Update for Windows 11 Cumulative Update for x64-based Systems" in order to use future patched Nvidia drivers.
We would be grateful if you could resolve these issues.
Please respectfully.

**Comment by dartraiden** [comment]
The certificate I used to sign was banned yesterday. Like many other similar certificates (they were stolen from their owners and circulated on the Internet)
https://news.sophos.com/en-us/2023/07/11/microsoft-revokes-malicious-drivers-in-patch-tuesday-culling/

Yes, there are still a small number of working certificates, but it's only a matter of time before they get banned too.

**Comment by wonheui** [comment]
Ah... that's right... TT.TT
If you can still fix it, I would appreciate it if you could edit the certificate and upload the patch file.
I respectfully request you.
please.~~~

**Comment by dartraiden** [comment]
<img width="583" alt="explorer_hMtaKxYk4v" src="https://github.com/dartraiden/NVIDIA-patcher/assets/5046855/d8959389-46c2-4075-8775-75a35edb6c3e">

**Comment by wonheui** [comment]
Sorry, but I don't have computer knowledge, so I don't understand what you mean.
Please explain in writing....ㅜ.ㅠ

**Comment by dartraiden** [comment]
Proof that certificate is revoked / blacklisted.

**Comment by wonheui** [comment]
ah...
I see what you mean...
Does that mean there is no way anymore?...ㅜ.ㅠ

**Comment by dartraiden** [comment]
Try latest [release](https://github.com/dartraiden/NVIDIA-patcher/releases).

**Comment by wonheui** [comment]
I already used the latest version 536.40.
The 536.40 version installation error is in the image above.
![2023-07-13 011850](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/3b8e89a0-2184-4ea8-8f12-aa9c990daa3f)

By the way, if you look at the release 536.40 you posted,
"Don't forget to add EVRootCA.crt to the Trusted Root Certification Authorities certificate store."
I don't know how to do this.
I would appreciate it if you could tell me how to add EVRootCA.crt to the Trusted Root Certification Authorities certificate store.

**Comment by wonheui** [comment]
Install the Windows update "July 2023 Cumulative Update for Windows 11 for x64-based Systems (KB5028182)".
After completely deleting the existing graphics driver,

I installed it as you said and it works fine.
Thank you very much for the detailed explanation.
I always support you.~~~^^

**Comment by dartraiden** [comment]
Well, let's hope this certificate doesn't get banned soon.

**Comment by wonheui** [comment]
thank you so much.~~👍😘😍

**Comment by wonheui** [comment]
Hello~ dartraiden~~
I would like to ask for one request.
With the "EVRootCA.crt" you uploaded, this certificate,
NVIDIA 536.40 version installed fine, but...
Because NVIDIA's new version is constantly uploaded...
(Current new version 536.67)
Like before...
I would appreciate it if you could make and upload it so that I can patch with "NVIDIA-patcher-master".
We respectfully request....

**Comment by wonheui** [comment]
Hello~ dartraiden~~
I would like to ask for one request.
With the "EVRootCA.crt" you uploaded, this certificate,
NVIDIA 536.40 version installed fine, but...
Because NVIDIA's new version is constantly uploaded...
(Current new version 536.67)
Like before...
I would appreciate it if you could make and upload it so that I can patch with "NVIDIA-patcher-master".
We respectfully request.... 
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/0b6c0263-a79e-4872-915c-1f2e5b0a7b5c)

**Comment by dartraiden** [comment]
Then this certificate will be blocked very quickly like the previous ones.

**Comment by wonheui** [comment]
then...
How do I install the new version of the NVIDIA driver?

**Comment by dartraiden** [comment]
https://github.com/dartraiden/NVIDIA-patcher/blob/master/docs/README.md

**Comment by wonheui** [comment]
You have already seen how to patch it.
"1. Download patched files from releases."
Do I have to wait for you to post every release?
I would appreciate it if you could upload the new version 536.67 (2023.7.18) release....

**Comment by wonheui** [comment]
if...
If you're worried about being blocked again...
I will share my Google Driver folder.
Can you upload a new version every time with my google driver folder?
Please respectfully.
https://drive.google.com/drive/folders/1J1oSm9P0Yrb6BK1riQ5MYT6SuFQHd9xk?usp=drive_link

**Comment by wonheui** [comment]
I only get installed on my computer.
I promise not to share.
Please respectfully....
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/7e24020a-c51b-4a72-86d4-5811c013062d)
![image](https://github.com/dartraiden/NVIDIA-patcher/assets/131703066/fb1997b0-5295-4cef-b1ff-38a99be66843)

**Comment by wonheui** [comment]
I mean, can't we patch with the certificate you shared a few days ago?
Of course, I will never share the shared certificate with anyone else, just in case.
However... you have to patch the new nvidia version to come, but as I previously asked dartraiden...
I am a Windows 11 user.
This is the person who inquired that patching could not be done because an error occurred when patching.
So, why not share only the new patched nvidia version with Google Driver?
I ask you politely....

**Comment by wonheui** [comment]
Can't you patch with the cert you shared a few days ago?
Of course, I don't share the shared certificate with anyone, just in case.
But...new nvidia versions require patches.
I am a Windows 11 user.
I previously contacted dartraiden about an error while patching on Windows 11.
That's why you can't patch on Windows 11.
Please share nvidia's latest patched version with google driver.
I promise never to share it with anyone else.
Sincerely please...
https://drive.google.com/drive/folders/1J1oSm9P0Yrb6BK1riQ5MYT6SuFQHd9xk?usp=drive_link
