### ISSUE TITLE
add fake gpu option

### ISSUE THREAD

**Issue by Sal-gamer** [dartraiden/NVIDIA-patcher#90]
I would like to ask that an option be implemented in which the driver identifies the gpu as if it were a commercial one, for example cmp50hx to be recognized as rtx2080ti for example, so games would accept it better, in some amd fsr 3.0 mods a resource is used to falsify gpu In games, bringing this feature to the driver would be good, you would probably be able to use ray cores and tensors more easily.

**Comment by Sal-gamer** [comment]
@dartraiden

**Comment by dartraiden** [comment]
What do you mean? You can easily change the name of the card in the device manager, but some games detect the card by vid/pid, and you can’t change them in Windows

**Comment by dartraiden** [comment]
Done in the latest release.
