### ISSUE TITLE
P104-100 + gt710 valorant ошибка A D3D11 -Compatible gpu (feature level 11, shader model 5.0) is required to run the engine.

### ISSUE THREAD

**Issue by Achtungboi** [dartraiden/NVIDIA-patcher#95]
Остальные игры работают как надо, драйвер стоит 472.12

**Comment by Achtungboi** [comment]
Проблема решена, скачиваем драйвер 417.21, mshybrid p104-100 - 2, gt710 - 1, adaptertype у p104-100 удаляем, перезагружаемся, в панели нвидиа выбираем высокопроизводительный процессор и радуемся)

**Comment by dartraiden** [comment]
Есть мнение, что их античиту не нравится подпись на dll-ках, поэтому игра их не загружает, а без них отваливается и 3D-ускорение.

Я могу попробовать подписать dll-ки другой подписью, но нужен доброволец для тестов (у меня на руках нет видеокарты сейчас).

**Comment by Achtungboi** [comment]
Времени много, давай попробуем.

**Comment by dartraiden** [comment]
Мой [клиент дискорда](https://miranda-ng.org/about/) не умеет в аудиовидео 😆 

https://disk.yandex.ru/d/ZfgfeBsSqMeY6g

Обязательно выбрать чистую установку в инсталляторе. Иначе винда может проявить ненужный ум и не установить, видя, что версия та же.

**Comment by Achtungboi** [comment]
Хорошо, завтра попробую. Может DDU удалить чтоб наверняка?

**Comment by dartraiden** [comment]
Можно и DDU без доступа в интернет. Хотя, разницы нет.

**Comment by Achtungboi** [comment]
Пошла установка, скину скрины подписей

**Comment by Achtungboi** [comment]
![Снимок экрана (35)](https://github.com/dartraiden/NVIDIA-patcher/assets/162019890/b6b80098-9065-43b8-8669-8b64aad62a66)
![Снимок экрана (36)](https://github.com/dartraiden/NVIDIA-patcher/assets/162019890/99ab1b36-abcf-4d72-8a30-5b201d6fa1c8)

Не сработало, видюхи ничего не поддерживают

**Comment by dartraiden** [comment]
Ага, оно не пропатчилось, я налажал с проверкой версий в пресетах...

**Comment by dartraiden** [comment]
Поправил пресеты, завтра сделаем ещё один "подход к снаряду".

**Comment by dartraiden** [comment]
https://disk.yandex.ru/d/7_-Z2Ay3RVE6hw

**Comment by Achtungboi** [comment]
Сегодня попробую

**Comment by Achtungboi** [comment]
пошёл проверять

**Comment by dartraiden** [comment]
Протестировать желательно, конечно, Valorant, какую-нибудь игру с [EAC](https://www.easy.ac/en-us/partners/), ну и [FaceIT](https://www.faceit.com/en/anti-cheat).

**Comment by Achtungboi** [comment]
с изиантичит вар тандер есть, фейсит чуть позже

**Comment by Achtungboi** [comment]
вар тандер работает, валорант ошибку выдаёт( , фейсит вроде работает
![Снимок экрана (55)](https://github.com/dartraiden/NVIDIA-patcher/assets/162019890/f3f4c540-e2e7-4372-bffe-3e4cf4e05ea9)

**Comment by Achtungboi** [comment]
Попробую ещё установить от 1070 драйвер, может поможет

**Comment by dartraiden** [comment]
Окей, попробуем сертификат, украденный у Take-Two

https://disk.yandex.ru/d/aKEgi-P9A-GiIg

**Comment by Achtungboi** [comment]
не сработало

**Comment by dartraiden** [comment]
Значит, не судьба, увы.

**Comment by Achtungboi** [comment]
На пробовать ещё. Написал в поддержку, решили что проблема не совсем в вангуарде. Сама игра сделана так, чтобы загружать только подписанные файлы, так что нужна подпись нвидиа на все файлы патчера. И если не сложно, можешь объяснить как патчить файлы, а то лучше сам позанимаюсь, чем буду тебя дёргать постоянно)

**Comment by Achtungboi** [comment]
Плюс в dxdiag-е 104-100 отображается как преобразователь, а не как видеокарта, и написано что подписи whql нет

**Comment by dartraiden** [comment]
Подпись NVIDIA и так есть на всех файлах.

Как патчить: запустить [_Start_Menu.bat](https://github.com/dartraiden/NVIDIA-patcher/blob/master/_Start_Menu.bat)
Но придётся включить тестовый режим. Если хочется без тестового режима, то нужен какой-нибудь украденный сертификат для подписи, я их не выкладываю в паблик.

Подписи WHQL. разумеется, нет и быть не может - её ставит Microsoft.

**Comment by Achtungboi** [comment]
@dartraiden 
Не знаю что я сделал, но у меня на 472 драйвере спокойно запустился валорант
![Снимок экрана (156)](https://github.com/dartraiden/NVIDIA-patcher/assets/162019890/647d0d7f-2f9f-4076-8cab-aae4ee231136)
![Снимок экрана (157)](https://github.com/dartraiden/NVIDIA-patcher/assets/162019890/5e9c6a5a-6769-4f68-abc7-db790b4a919c)
![Снимок экрана (158)](https://github.com/dartraiden/NVIDIA-patcher/assets/162019890/396fa157-14a5-45c8-9d20-99b2bf7e673f)

**Comment by dartraiden** [comment]
Всё, что угодно может быть, вполне там может быть условие, "если версия выше xxx и подпись некошерная, то атятя"

**Comment by Achtungboi** [comment]
так в том-то и дело, что по сравнению с предыдущими попытками я ничего не менял
