### ISSUE TITLE
hopes to add graphics cards like the 3070M

### ISSUE THREAD

**Issue by GreenDamTan** [dartraiden/NVIDIA-patcher#98]
![20240312012743](https://github.com/dartraiden/NVIDIA-patcher/assets/4781595/11bfd482-1222-4f50-aa68-aabc320000ce)
graphics cards such as the 3070m also require driver modifications for installation
it would be nice to add that too

3070M 10DE249D 10DE0000
3060M 10DE2520 10DE0000

**Comment by dartraiden** [comment]
https://github.com/arutar/FrankenDriver

**Comment by GreenDamTan** [comment]
> https://github.com/arutar/FrankenDriver

but that one doesnt support 40HX

**Comment by dartraiden** [comment]
FrankenDriver with P106-090 / P106-100 / P104-100 / P104-101 / P102-100 / CMP 30HX / CMP 40HX / CMP 50HX / CMP 70HX / CMP 90HX / CMP 170HX support

https://disk.yandex.ru/d/OwUxD_jVKcjiFA
